import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { DocumentIcon } from "../icons";
import { AuthorizationDocumentsPanel } from "../components/AuthorizationDocumentsPanel";
import { AppApiError } from "../../services/appApi";
import { createAuthorization, getAuthorization, getAuthorizationOptions, updateAuthorization, type AuthorizationDetail, type AuthorizationFields, type AuthorizationOptions, type PortfolioAuthorizationEditableStatus, type PortfolioAuthorizationStatus, type PortfolioAuthorizationType } from "../../services/authorizationsApi";

interface Props { organizationId: string; canCreate: boolean; canUpdate: boolean; }
const types: Array<[PortfolioAuthorizationType, string]> = [["sale", "Venda"], ["rent", "Locação"], ["sale_rent", "Venda ou locação"], ["capture", "Captação"]];
const editableStatuses: Array<[PortfolioAuthorizationEditableStatus, string]> = [["draft", "Rascunho"], ["awaiting_data", "Aguardando dados"], ["sent", "Enviado"], ["signed", "Assinado"], ["active", "Vigente"], ["canceled", "Cancelado"]];
const statusLabels: Record<PortfolioAuthorizationStatus, string> = { draft: "Rascunho", awaiting_data: "Aguardando dados", sent: "Enviado", signed: "Assinado", active: "Vigente", expiring: "Vencendo", expired: "Vencido", canceled: "Cancelado" };
function readId() { return new URLSearchParams(globalThis.location.search).get("id")?.trim() || null; }
function readPropertyId() { return new URLSearchParams(globalThis.location.search).get("propertyId")?.trim() || null; }
function emptyFields(): AuthorizationFields { return { type: "sale", status: "draft", exclusive: false, commissionPercent: null, startsAt: null, endsAt: null, responsibleMembershipId: null, notes: null, cancelReason: null }; }
function historyLabel(type: string) { if (type === "authorization.created") return "Autorização criada"; if (type === "authorization.status_changed") return "Status alterado"; if (type === "authorization.updated") return "Autorização atualizada"; if (type === "authorization.document.generated") return "Nova versão de documento gerada"; if (type === "authorization.signature.prepared") return "Assinatura eletrônica preparada"; if (type === "authorization.signature.canceled") return "Preparação de assinatura cancelada"; return "Atualização da autorização"; }
function changesText(data: Record<string, unknown>) { if (typeof data.identifier === "string" && typeof data.version === "number") return `Versão ${data.version} · ${data.identifier}`; if (typeof data.signerCount === "number") return `${data.signerCount} signatário(s) congelado(s) para esta preparação.`; if (typeof data.requestId === "string" && typeof data.documentId === "string") return "A preparação vinculada à versão do documento foi cancelada."; const changes = data.changes; if (!changes || typeof changes !== "object" || Array.isArray(changes)) return ""; const labels: Record<string, string> = { type: "tipo", status: "status", exclusive: "exclusividade", commissionPercent: "comissão", startsAt: "início", endsAt: "fim", responsibleMembershipId: "responsável", notes: "observações", cancelReason: "motivo do cancelamento" }; return `Campos alterados: ${Object.keys(changes as Record<string, unknown>).map((key) => labels[key] ?? key).join(", ")}.`; }

export function AuthorizationEditorPage({ organizationId, canCreate, canUpdate }: Props) {
  const authorizationId = useMemo(readId, []);
  const initialPropertyId = useMemo(readPropertyId, []);
  const [options, setOptions] = useState<AuthorizationOptions | null>(null);
  const [detail, setDetail] = useState<AuthorizationDetail | null>(null);
  const [propertyId, setPropertyId] = useState(initialPropertyId ?? "");
  const [draft, setDraft] = useState<AuthorizationFields>(emptyFields());
  const [baseline, setBaseline] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const dirty = baseline !== "" && baseline !== JSON.stringify({ propertyId, draft });
  const set = <K extends keyof AuthorizationFields>(key: K, value: AuthorizationFields[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const selectedProperty = options?.properties.find((property) => property.id === propertyId) ?? null;

  const applyPropertyDefaults = useCallback((selectedId: string, available: AuthorizationOptions | null, preserve = false) => {
    const property = available?.properties.find((item) => item.id === selectedId);
    if (!property) return;
    setDraft((current) => ({ ...current, type: preserve ? current.type : property.purpose, responsibleMembershipId: preserve ? current.responsibleMembershipId : property.responsibleMembershipId, startsAt: preserve ? current.startsAt : property.authorizationStartsAt, endsAt: preserve ? current.endsAt : property.authorizationEndsAt, commissionPercent: preserve ? current.commissionPercent : property.commissionPercent, exclusive: preserve ? current.exclusive : property.exclusive }));
  }, []);

  useEffect(() => { let alive = true; setLoading(true); setError(null); Promise.all([getAuthorizationOptions(organizationId), authorizationId ? getAuthorization(organizationId, authorizationId) : Promise.resolve(null)]).then(([loadedOptions, loadedDetail]) => { if (!alive) return; setOptions(loadedOptions); if (loadedDetail) { setDetail(loadedDetail); setPropertyId(loadedDetail.property.id); const fields: AuthorizationFields = { type: loadedDetail.type, status: loadedDetail.baseStatus, exclusive: loadedDetail.exclusive, commissionPercent: loadedDetail.commissionPercent, startsAt: loadedDetail.startsAt, endsAt: loadedDetail.endsAt, responsibleMembershipId: loadedDetail.responsible?.membershipId ?? null, notes: loadedDetail.notes, cancelReason: loadedDetail.cancelReason }; setDraft(fields); setBaseline(JSON.stringify({ propertyId: loadedDetail.property.id, draft: fields })); } else { const chosen = initialPropertyId && loadedOptions.properties.some((property) => property.id === initialPropertyId) ? initialPropertyId : loadedOptions.properties[0]?.id ?? ""; setPropertyId(chosen); const property = loadedOptions.properties.find((item) => item.id === chosen); const fields = emptyFields(); if (property) { fields.type = property.purpose; fields.responsibleMembershipId = property.responsibleMembershipId; fields.startsAt = property.authorizationStartsAt; fields.endsAt = property.authorizationEndsAt; fields.commissionPercent = property.commissionPercent; fields.exclusive = property.exclusive; } setDraft(fields); setBaseline(JSON.stringify({ propertyId: chosen, draft: fields })); } }).catch((loadError) => { if (alive) setError(loadError instanceof AppApiError ? loadError.message : "Não foi possível carregar a autorização."); }).finally(() => { if (alive) setLoading(false); }); return () => { alive = false; }; }, [organizationId, authorizationId, initialPropertyId]);
  useEffect(() => { const listener = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; globalThis.addEventListener("beforeunload", listener); return () => globalThis.removeEventListener("beforeunload", listener); }, [dirty]);

  async function submit(event: FormEvent) {
    event.preventDefault(); if (saving) return; setError(null); setSuccess(null);
    if (!propertyId) { setError("Selecione um imóvel."); return; }
    if (draft.status === "active" && (!draft.startsAt || !draft.endsAt)) { setError("Para marcar como vigente, informe início e fim da autorização."); return; }
    if (draft.status === "canceled" && !draft.cancelReason?.trim()) { setError("Informe o motivo do cancelamento."); return; }
    if (!selectedProperty?.owners.length && !detail?.parties.length) { setError("O imóvel precisa ter ao menos um proprietário antes da autorização."); return; }
    setSaving(true);
    try {
      const saved = authorizationId ? await updateAuthorization(organizationId, authorizationId, draft) : await createAuthorization(organizationId, propertyId, draft);
      setDetail(saved); setPropertyId(saved.property.id); const fields: AuthorizationFields = { type: saved.type, status: saved.baseStatus, exclusive: saved.exclusive, commissionPercent: saved.commissionPercent, startsAt: saved.startsAt, endsAt: saved.endsAt, responsibleMembershipId: saved.responsible?.membershipId ?? null, notes: saved.notes, cancelReason: saved.cancelReason }; setDraft(fields); setBaseline(JSON.stringify({ propertyId: saved.property.id, draft: fields })); setSuccess(authorizationId ? "Autorização atualizada." : "Autorização criada."); if (!authorizationId) globalThis.history.replaceState(null, "", `/app/autorizacao/?id=${encodeURIComponent(saved.id)}`);
    } catch (saveError) { setError(saveError instanceof AppApiError ? saveError.message : "Não foi possível salvar a autorização."); } finally { setSaving(false); }
  }

  if (loading) return <div className="app-table-empty"><span className="app-spinner"/>Carregando autorização...</div>;
  const canSave = authorizationId ? canUpdate : canCreate;
  const parties = detail?.parties ?? selectedProperty?.owners.map((owner) => ({ ...owner, role: "owner" as const, signerRequired: true })) ?? [];
  const effectiveStatus = detail?.status ?? draft.status;
  return <form onSubmit={(event) => void submit(event)} className="app-editor-form">
    <section className="app-page-heading app-page-heading--editor"><div><span className="app-section-eyebrow">Portfólio · Autorizações</span><h1>{detail ? `Autorização — ${detail.property.title}` : "Nova autorização"}</h1><p>{detail ? `${detail.property.internalCode} · ${statusLabels[effectiveStatus]}` : "Vincule condições de comercialização a um imóvel e preserve o histórico."}</p></div><div className="app-heading-actions"><a className="app-secondary-button" href="/app/autorizacoes/">Voltar</a>{dirty && <span className="app-unsaved-badge">Alterações não salvas</span>}{canSave && <button className="app-primary-button" type="submit" disabled={saving}>{saving ? "Salvando..." : "Salvar"}</button>}</div></section>
    {error && <div className="app-inline-error">{error}</div>}{success && <div className="app-inline-success">{success}</div>}
    <section className="app-data-card app-authorization-editor-card"><header className="app-card-header"><div><DocumentIcon/><strong>Dados da autorização</strong></div>{detail && <em className={`app-status-pill authorization-${effectiveStatus}`}>{statusLabels[effectiveStatus]}</em>}</header><div className="app-form-section"><div className="app-form-grid"><label className="app-form-span-2"><span>Imóvel *</span><select value={propertyId} disabled={Boolean(authorizationId)} onChange={(event) => { setPropertyId(event.target.value); applyPropertyDefaults(event.target.value, options); }}>{options?.properties.map((property) => <option key={property.id} value={property.id}>{property.internalCode} · {property.title}</option>)}</select></label><label><span>Tipo *</span><select value={draft.type} onChange={(event) => set("type", event.target.value as PortfolioAuthorizationType)}>{types.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Status *</span><select value={draft.status} onChange={(event) => set("status", event.target.value as PortfolioAuthorizationEditableStatus)}>{editableStatuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Responsável</span><select value={draft.responsibleMembershipId ?? ""} onChange={(event) => set("responsibleMembershipId", event.target.value || null)}><option value="">Eu (padrão)</option>{options?.assignees.map((assignee) => <option key={assignee.membershipId} value={assignee.membershipId}>{assignee.displayName}</option>)}</select></label><label><span>Comissão (%)</span><input type="number" min="0" max="100" step="0.01" value={draft.commissionPercent ?? ""} onChange={(event) => set("commissionPercent", event.target.value || null)}/></label><label><span>Início</span><input type="date" value={draft.startsAt ?? ""} onChange={(event) => set("startsAt", event.target.value || null)}/></label><label><span>Fim</span><input type="date" value={draft.endsAt ?? ""} onChange={(event) => set("endsAt", event.target.value || null)}/></label></div><label className="app-inline-check app-authorization-exclusive"><input type="checkbox" checked={draft.exclusive} onChange={(event) => set("exclusive", event.target.checked)}/> Autorização com exclusividade</label><label className="app-block-label"><span>Observações internas</span><textarea rows={5} value={draft.notes ?? ""} onChange={(event) => set("notes", event.target.value || null)} placeholder="Condições, exceções, pendências documentais ou observações da negociação."/></label>{draft.status === "canceled" && <label className="app-block-label"><span>Motivo do cancelamento *</span><textarea rows={3} value={draft.cancelReason ?? ""} onChange={(event) => set("cancelReason", event.target.value || null)} placeholder="Informe por que esta autorização foi cancelada."/></label>}</div></section>
    <section className="app-data-card"><header className="app-card-header"><div><strong>Proprietários / partes</strong><small>Os proprietários são copiados do imóvel no momento da criação para preservar o vínculo histórico.</small></div></header><div className="app-authorization-parties">{!parties.length ? <div className="app-soft-empty">O imóvel ainda não possui proprietário vinculado. Volte ao cadastro do imóvel antes de criar a autorização.</div> : parties.map((party) => <article key={party.contactId}><div><strong>{party.name}</strong><span>{party.primary ? "Proprietário principal" : "Proprietário"}</span></div><div><span>{party.email ?? "Sem e-mail"}</span><span>{party.phone ?? "Sem telefone"}</span></div><div><span>Participação</span><strong>{party.ownershipPercentage ? `${Number(party.ownershipPercentage).toLocaleString("pt-BR")}%` : "Não informada"}</strong></div></article>)}</div></section>
    {detail ? <AuthorizationDocumentsPanel organizationId={organizationId} authorizationId={detail.id} canGenerate={canUpdate} dirty={dirty} authorizationStatus={detail.baseStatus} onGenerated={async () => { const refreshed = await getAuthorization(organizationId, detail.id); setDetail(refreshed); }}/> : <section className="app-context-banner"><DocumentIcon/><div><strong>Documento e assinatura</strong><p>Salve a autorização primeiro. Depois será possível gerar versões imutáveis em PDF com identificador e hash de integridade.</p></div></section>}
    {detail && <section className="app-timeline app-data-card"><header><strong>Histórico da autorização</strong><span>{detail.timeline.length} eventos</span></header>{detail.timeline.length ? detail.timeline.map((event) => <article key={event.id}><span className="app-timeline-dot"/><div><strong>{historyLabel(event.eventType)}</strong>{changesText(event.data) && <p>{changesText(event.data)}</p>}<small>{event.actor?.displayName ?? "Sistema"}</small></div><time>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(event.createdAt))}</time></article>) : <div className="app-soft-empty">Nenhum evento registrado ainda.</div>}</section>}
  </form>;
}
