import { useEffect, useMemo, useState } from "react";
import { ContractIcon, SearchIcon } from "../icons";
import { AppApiError } from "../../services/appApi";
import { listCorporateContracts, type CorporateContractListResult, type CorporateContractStatus, type CorporateContractType } from "../../services/contractsApi";

interface Props { organizationId: string; canCreate: boolean; }
export const contractStatusLabels: Record<CorporateContractStatus, string> = { draft: "Rascunho", review: "Em revisão", approved: "Aprovado", sent: "Enviado", signed: "Assinado", active: "Vigente", closed: "Encerrado", canceled: "Cancelado" };
export const contractTypeLabels: Record<CorporateContractType, string> = { sale_purchase: "Compra e venda", rent: "Locação", administration: "Administração", intermediation: "Intermediação", capture: "Captação", exclusivity: "Exclusividade", services: "Prestação de serviços", other: "Outro" };
function money(value: string | null) { if (!value) return "—"; return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value)); }
function dateLabel(value: string | null) { if (!value) return "—"; return new Intl.DateTimeFormat("pt-BR").format(new Date(`${value}T12:00:00`)); }

export function ContractsPage({ organizationId, canCreate }: Props) {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState<CorporateContractStatus | "">("");
  const [type, setType] = useState<CorporateContractType | "">("");
  const [view, setView] = useState<"all" | "mine">("all");
  const [page, setPage] = useState(1);
  const [result, setResult] = useState<CorporateContractListResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const query = useMemo(() => ({ search: search.trim() || undefined, status: status || undefined, type: type || undefined, view, page, pageSize: 50 }), [search, status, type, view, page]);
  useEffect(() => { const handle = globalThis.setTimeout(() => { setLoading(true); setError(null); void listCorporateContracts(organizationId, query).then(setResult).catch((loadError) => setError(loadError instanceof AppApiError ? loadError.message : "Não foi possível carregar os contratos.")).finally(() => setLoading(false)); }, 220); return () => globalThis.clearTimeout(handle); }, [organizationId, query]);
  return <>
    <section className="app-page-heading"><div><span className="app-section-eyebrow">Gestão corporativa</span><h1>Contratos gerados</h1><p>Centralize contratos vinculados ao imóvel e ao negócio, com partes, valores, vigência e versionamento.</p></div>{canCreate && <a className="app-primary-button" href="/app/contrato/">+ Novo contrato</a>}</section>
    {error && <div className="app-inline-error">{error}</div>}
    <section className="app-metrics app-metrics--compact app-contract-metrics">{[["Total de contratos", result?.total ?? 0], ["Rascunhos", result?.drafts ?? 0], ["Vigentes", result?.active ?? 0], ["Assinatura pendente", result?.pendingSignature ?? 0], ["A vencer (30 dias)", result?.expiring ?? 0]].map(([label, value]) => <article className="app-metric-card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className="app-filter-panel app-contract-filters"><div className="app-search-field"><SearchIcon/><input placeholder="Contrato, imóvel, código ou parte..." value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }}/></div><select aria-label="Status" value={status} onChange={(event) => { setStatus(event.target.value as CorporateContractStatus | ""); setPage(1); }}><option value="">Todos os status</option>{Object.entries(contractStatusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Tipo" value={type} onChange={(event) => { setType(event.target.value as CorporateContractType | ""); setPage(1); }}><option value="">Todos os tipos</option>{Object.entries(contractTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><div className="app-segmented"><button type="button" className={view === "all" ? "is-active" : ""} onClick={() => { setView("all"); setPage(1); }}>Todos</button><button type="button" className={view === "mine" ? "is-active" : ""} onClick={() => { setView("mine"); setPage(1); }}>Meus</button></div>{(search || status || type || view === "mine") && <button className="app-secondary-button" type="button" onClick={() => { setSearch(""); setStatus(""); setType(""); setView("all"); setPage(1); }}>Limpar</button>}</section>
    <section className="app-data-card">{loading ? <div className="app-table-empty"><span className="app-spinner"/>Carregando contratos...</div> : !result?.items.length ? <div className="app-table-empty"><ContractIcon/><h2>Nenhum contrato encontrado</h2><p>Crie o primeiro contrato ou ajuste os filtros selecionados.</p>{canCreate && <a className="app-primary-button" href="/app/contrato/">Criar primeiro contrato</a>}</div> : <><div className="app-contract-table"><header><span>Contrato</span><span>Imóvel</span><span>Contraparte</span><span>Tipo</span><span>Valor</span><span>Versão</span><span>Fim</span><span>Status</span><span>Responsável</span></header>{result.items.map((item) => <a key={item.id} href={`/app/contrato/?id=${encodeURIComponent(item.id)}`}><span><strong>{item.title}</strong><small>{item.opportunity?.title ?? "Sem oportunidade vinculada"}</small></span><span><strong>{item.property.title}</strong><small>{item.property.internalCode}</small></span><span>{item.counterparty?.name ?? "—"}</span><span>{contractTypeLabels[item.type]}</span><span>{money(item.amount)}</span><span>V{String(item.currentVersion).padStart(2, "0")}</span><span>{dateLabel(item.endsAt)}</span><span><em className={`app-status-pill contract-${item.status}`}>{contractStatusLabels[item.status]}</em></span><span>{item.responsible?.displayName ?? "—"}</span></a>)}</div><div className="app-pagination"><span>{result.totalItems} {result.totalItems === 1 ? "contrato" : "contratos"}</span><div><button type="button" disabled={result.page <= 1 || loading} onClick={() => setPage((current) => Math.max(1, current - 1))}>Anterior</button><span>{result.page} / {result.totalPages}</span><button type="button" disabled={result.page >= result.totalPages || loading} onClick={() => setPage((current) => current + 1)}>Próxima</button></div></div></>}</section>
  </>;
}
