import { useCallback, useEffect, useMemo, useState } from "react";
import { ContractIcon, SearchIcon } from "../icons";
import { AppApiError } from "../../services/appApi";
import { deleteCorporateContract, listCorporateContracts, type CorporateContractListResult, type CorporateContractStatus, type CorporateContractType } from "../../services/contractsApi";

interface Props { organizationId:string; canCreate:boolean; canUpdate?:boolean }
export const contractStatusLabels:Record<CorporateContractStatus,string>={draft:"Rascunho",review:"Em revisão",approved:"Aprovado",sent:"Enviado",signed:"Assinado",active:"Vigente",closed:"Encerrado",canceled:"Cancelado"};
export const contractTypeLabels:Record<CorporateContractType,string>={sale_purchase:"Compra e venda",rent:"Locação",administration:"Administração",intermediation:"Intermediação",capture:"Captação",exclusivity:"Exclusividade",services:"Prestação de serviços",other:"Outro"};
function money(value:string|null){return value?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value)):"—"}
function dateLabel(value:string|null){return value?new Intl.DateTimeFormat("pt-BR").format(new Date(value+"T12:00:00")):"—"}

export function ContractsPage({organizationId,canCreate,canUpdate=canCreate}:Props){
 const[search,setSearch]=useState("");const[status,setStatus]=useState<CorporateContractStatus|"">("");const[type,setType]=useState<CorporateContractType|"">("");const[view,setView]=useState<"all"|"mine">("all");const[page,setPage]=useState(1);const[result,setResult]=useState<CorporateContractListResult|null>(null);const[loading,setLoading]=useState(true);const[deletingId,setDeletingId]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const query=useMemo(()=>({search:search.trim()||undefined,status:status||undefined,type:type||undefined,view,page,pageSize:50}),[search,status,type,view,page]);
 const load=useCallback(async(showLoading=true)=>{if(showLoading)setLoading(true);setError(null);try{setResult(await listCorporateContracts(organizationId,query))}catch(e){setError(e instanceof AppApiError?e.message:"Não foi possível carregar os contratos.")}finally{if(showLoading)setLoading(false)}},[organizationId,query]);
 useEffect(()=>{const h=globalThis.setTimeout(()=>void load(),220);return()=>globalThis.clearTimeout(h)},[load]);
 async function remove(id:string,title:string){if(!globalThis.confirm('Excluir o contrato "'+title+'"? O histórico será preservado.'))return;setDeletingId(id);setError(null);try{await deleteCorporateContract(organizationId,id);setResult(current=>current?{...current,items:current.items.filter(item=>item.id!==id),totalItems:Math.max(0,current.totalItems-1),total:Math.max(0,current.total-1)}:current);void load(false)}catch(e){setError(e instanceof AppApiError?e.message:"Não foi possível excluir o contrato.")}finally{setDeletingId(null)}}
 return <>
 <section className="app-page-heading"><div><span className="app-section-eyebrow">Gestão corporativa</span><h1>Contratos gerados</h1><p>Centralize contratos vinculados ao imóvel e ao negócio, com partes, valores, vigência e versionamento.</p></div>{canCreate&&<a className="app-primary-button" href="/app/contrato/">+ Novo contrato</a>}</section>
 {error&&<div className="app-inline-error">{error}</div>}
 <section className="app-metrics app-metrics--compact app-contract-metrics">{[["Total de contratos",result?.total??0],["Rascunhos",result?.drafts??0],["Vigentes",result?.active??0],["Assinatura pendente",result?.pendingSignature??0],["A vencer (30 dias)",result?.expiring??0]].map(([label,value])=><article className="app-metric-card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
 <section className="app-filter-panel app-contract-filters"><div className="app-search-field"><SearchIcon/><input placeholder="Contrato, imóvel, código ou parte..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><select value={status} onChange={e=>{setStatus(e.target.value as CorporateContractStatus|"");setPage(1)}}><option value="">Todos os status</option>{Object.entries(contractStatusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={type} onChange={e=>{setType(e.target.value as CorporateContractType|"");setPage(1)}}><option value="">Todos os tipos</option>{Object.entries(contractTypeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="app-segmented"><button type="button" className={view==="all"?"is-active":""} onClick={()=>setView("all")}>Todos</button><button type="button" className={view==="mine"?"is-active":""} onClick={()=>setView("mine")}>Meus</button></div></section>
 <section className="app-data-card">{loading?<div className="app-table-empty"><span className="app-spinner"/>Carregando contratos...</div>:!result?.items.length?<div className="app-table-empty"><ContractIcon/><h2>Nenhum contrato encontrado</h2><p>Crie o primeiro contrato ou ajuste os filtros.</p></div>:<><div className="app-contract-table app-action-table"><header><span>Contrato</span><span>Imóvel</span><span>Contraparte</span><span>Tipo</span><span>Valor</span><span>Versão</span><span>Fim</span><span>Status</span><span>Ações</span></header>{result.items.map(item=><div className="app-action-table-row" key={item.id}><span><strong>{item.title}</strong><small>{item.opportunity?.title??"Sem oportunidade vinculada"}</small></span><span><strong>{item.property.title}</strong><small>{item.property.internalCode}</small></span><span>{item.counterparty?.name??"—"}</span><span>{contractTypeLabels[item.type]}</span><span>{money(item.amount)}</span><span>V{String(item.currentVersion).padStart(2,"0")}</span><span>{dateLabel(item.endsAt)}</span><span><em className={"app-status-pill contract-"+item.status}>{contractStatusLabels[item.status]}</em></span><span className="app-row-actions"><a className="app-secondary-button" href={"/app/contrato/?id="+encodeURIComponent(item.id)}>Editar</a>{canUpdate&&<button className="app-secondary-button is-danger" type="button" disabled={deletingId===item.id} onClick={()=>void remove(item.id,item.title)}>{deletingId===item.id?"Excluindo...":"Excluir"}</button>}</span></div>)}</div><div className="app-pagination"><span>{result.totalItems} contratos</span><div><button type="button" disabled={result.page<=1||loading} onClick={()=>setPage(v=>Math.max(1,v-1))}>Anterior</button><span>{result.page} / {result.totalPages}</span><button type="button" disabled={result.page>=result.totalPages||loading} onClick={()=>setPage(v=>v+1)}>Próxima</button></div></div></>}</section>
 </>;
}
