import { useCallback, useEffect, useMemo, useState } from "react";
import { ClipboardIcon, SearchIcon } from "../icons";
import { AppApiError } from "../../services/appApi";
import { deleteCorporateInspection, listCorporateInspections, type CorporateInspectionListResult, type CorporateInspectionStatus, type CorporateInspectionType } from "../../services/inspectionsApi";
interface Props{organizationId:string;canCreate:boolean;canUpdate?:boolean}
export const inspectionStatusLabels:Record<CorporateInspectionStatus,string>={draft:"Rascunho",in_progress:"Em execução",review:"Em revisão",completed:"Concluído",canceled:"Cancelado"};
export const inspectionTypeLabels:Record<CorporateInspectionType,string>={entry:"Entrada",exit:"Saída",valuation:"Avaliação",technical:"Inspeção técnica",handover:"Entrega",custom:"Personalizado"};
function dateTimeLabel(value:string|null){return value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—"}
export function InspectionsPage({organizationId,canCreate,canUpdate=canCreate}:Props){
 const[search,setSearch]=useState("");const[status,setStatus]=useState<CorporateInspectionStatus|"">("");const[type,setType]=useState<CorporateInspectionType|"">("");const[view,setView]=useState<"all"|"mine">("all");const[page,setPage]=useState(1);const[result,setResult]=useState<CorporateInspectionListResult|null>(null);const[loading,setLoading]=useState(true);const[deletingId,setDeletingId]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const query=useMemo(()=>({search:search.trim()||undefined,status:status||undefined,type:type||undefined,view,page,pageSize:50}),[search,status,type,view,page]);
 const load=useCallback(async(showLoading=true)=>{if(showLoading)setLoading(true);setError(null);try{setResult(await listCorporateInspections(organizationId,query))}catch(e){setError(e instanceof AppApiError?e.message:"Não foi possível carregar os laudos e vistorias.")}finally{if(showLoading)setLoading(false)}},[organizationId,query]);
 useEffect(()=>{const h=globalThis.setTimeout(()=>void load(),220);return()=>globalThis.clearTimeout(h)},[load]);
 async function remove(id:string,title:string){if(!globalThis.confirm('Excluir "'+title+'"? O histórico será preservado.'))return;setDeletingId(id);setError(null);try{await deleteCorporateInspection(organizationId,id);setResult(current=>current?{...current,items:current.items.filter(item=>item.id!==id),totalItems:Math.max(0,current.totalItems-1),total:Math.max(0,current.total-1)}:current);void load(false)}catch(e){setError(e instanceof AppApiError?e.message:"Não foi possível excluir o laudo ou vistoria.")}finally{setDeletingId(null)}}
 return <>
 <section className="app-page-heading"><div><span className="app-section-eyebrow">Gestão corporativa</span><h1>Laudos & vistorias</h1><p>Registre a condição do imóvel com ambientes, itens, medições, histórico e versionamento do laudo.</p></div>{canCreate&&<a className="app-primary-button" href="/app/vistoria/">+ Nova vistoria</a>}</section>
 {error&&<div className="app-inline-error">{error}</div>}
 <section className="app-metrics app-metrics--compact app-inspection-metrics">{[["Total",result?.total??0],["Rascunhos",result?.drafts??0],["Em execução",result?.inProgress??0],["Em revisão",result?.review??0],["Concluídos",result?.completed??0]].map(([label,value])=><article className="app-metric-card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
 <section className="app-filter-panel app-inspection-filters"><div className="app-search-field"><SearchIcon/><input placeholder="Laudo, imóvel ou código..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><select value={status} onChange={e=>{setStatus(e.target.value as CorporateInspectionStatus|"");setPage(1)}}><option value="">Todos os status</option>{Object.entries(inspectionStatusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={type} onChange={e=>{setType(e.target.value as CorporateInspectionType|"");setPage(1)}}><option value="">Todos os tipos</option>{Object.entries(inspectionTypeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="app-segmented"><button type="button" className={view==="all"?"is-active":""} onClick={()=>setView("all")}>Todos</button><button type="button" className={view==="mine"?"is-active":""} onClick={()=>setView("mine")}>Meus</button></div></section>
 <section className="app-data-card app-inspection-list-card">{loading?<div className="app-table-empty"><span className="app-spinner"/>Carregando laudos e vistorias...</div>:!result?.items.length?<div className="app-table-empty"><ClipboardIcon/><h2>Nenhum laudo ou vistoria encontrado</h2><p>Crie a primeira vistoria ou ajuste os filtros.</p></div>:<><div className="app-inspection-table app-action-table"><header><span>Laudo / vistoria</span><span>Imóvel</span><span>Tipo</span><span>Estrutura</span><span>Agendamento</span><span>Versão</span><span>Status</span><span>Ações</span></header>{result.items.map(item=><div className="app-action-table-row" key={item.id}><span><strong>{item.title}</strong><small>{item.contract?.title??item.visit?.title??"Sem vínculo complementar"}</small></span><span><strong>{item.property.title}</strong><small>{item.property.internalCode}</small></span><span>{inspectionTypeLabels[item.type]}</span><span>{item.environmentCount} amb. · {item.itemCount} itens</span><span>{dateTimeLabel(item.scheduledAt)}</span><span>V{String(item.currentVersion).padStart(2,"0")}</span><span><em className={"app-status-pill inspection-"+item.status}>{inspectionStatusLabels[item.status]}</em></span><span className="app-row-actions"><a className="app-secondary-button" href={"/app/vistoria/?id="+encodeURIComponent(item.id)}>Editar</a>{canUpdate&&<button className="app-secondary-button is-danger" type="button" disabled={deletingId===item.id} onClick={()=>void remove(item.id,item.title)}>{deletingId===item.id?"Excluindo...":"Excluir"}</button>}</span></div>)}</div><div className="app-pagination"><span>{result.totalItems} registros</span><div><button type="button" disabled={result.page<=1||loading} onClick={()=>setPage(v=>Math.max(1,v-1))}>Anterior</button><span>{result.page} / {result.totalPages}</span><button type="button" disabled={result.page>=result.totalPages||loading} onClick={()=>setPage(v=>v+1)}>Próxima</button></div></div></>}</section>
 </>;
}
