import { useEffect, useMemo, useState } from "react";
import { BuildingIcon, SearchIcon } from "../icons";
import { AppApiError } from "../../services/appApi";
import { archiveProperty, listProperties, restoreProperty, type PropertyListResult, type PropertyPurpose, type PropertyStatus, type PropertyType } from "../../services/propertiesApi";

interface Props { organizationId: string; canCreate: boolean; canUpdate?: boolean }
const statusLabels: Record<PropertyStatus,string> = { draft:"Rascunho", registering:"Em cadastro", awaiting_documents:"Aguardando documentos", evaluation:"Em avaliação", active:"Ativo", reserved:"Reservado", sold:"Vendido", rented:"Alugado", suspended:"Suspenso", inactive:"Inativo" };
const purposeLabels: Record<PropertyPurpose,string> = { sale:"Venda", rent:"Aluguel", sale_rent:"Venda ou aluguel" };
const typeLabels: Record<PropertyType,string> = { apartment:"Apartamento", house:"Casa", commercial:"Comercial", land:"Terreno", rural:"Rural", warehouse:"Galpão", building:"Prédio", room:"Sala", other:"Outro" };
function money(value:string|null){if(!value)return"—";return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(value))}

export function PropertiesPage({organizationId,canCreate,canUpdate}:Props){
  canUpdate=canUpdate??canCreate;
  const [search,setSearch]=useState(""); const [status,setStatus]=useState<PropertyStatus|"">(""); const [purpose,setPurpose]=useState<PropertyPurpose|"">(""); const [type,setType]=useState<PropertyType|"">(""); const [archived,setArchived]=useState<"exclude"|"only">("exclude"); const [selectedId,setSelectedId]=useState(""); const [reloadKey,setReloadKey]=useState(0);
  const [result,setResult]=useState<PropertyListResult|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null);
  const query=useMemo(()=>({search:search.trim()||undefined,status:status||undefined,purpose:purpose||undefined,type:type||undefined,archived,pageSize:50}),[search,status,purpose,type,archived]);
  useEffect(()=>{const handle=globalThis.setTimeout(()=>{setLoading(true);setError(null);void listProperties(organizationId,query).then(value=>{setResult(value);setSelectedId(current=>value.items.some(item=>item.id===current)?current:"")}).catch(error=>setError(error instanceof AppApiError?error.message:"Não foi possível carregar o catálogo.")).finally(()=>setLoading(false))},250);return()=>globalThis.clearTimeout(handle)},[organizationId,query,reloadKey]);
  async function changeLifecycle(){if(!selectedId)return;const action=archived==="only"?"restaurar":"arquivar";if(!globalThis.confirm("Deseja "+action+" o imóvel selecionado?"))return;setBusy(true);setError(null);setNotice(null);try{if(archived==="only")await restoreProperty(organizationId,selectedId);else await archiveProperty(organizationId,selectedId);setNotice(archived==="only"?"Imóvel restaurado com sucesso.":"Imóvel arquivado com sucesso.");setSelectedId("");setReloadKey(value=>value+1)}catch(error){setError(error instanceof AppApiError?error.message:"Não foi possível "+action+" o imóvel.")}finally{setBusy(false)}}
  async function changeItemLifecycle(id:string,title:string,isArchived:boolean){const action=isArchived?"restaurar":"excluir";if(!globalThis.confirm(`${action === "excluir" ? "Excluir" : "Restaurar"} o imóvel "${title}"? ${action === "excluir" ? "O registro será arquivado e o histórico preservado." : ""}`))return;setBusy(true);setError(null);setNotice(null);try{if(isArchived)await restoreProperty(organizationId,id);else await archiveProperty(organizationId,id);setNotice(isArchived?"Imóvel restaurado com sucesso.":"Imóvel excluído da listagem ativa.");setReloadKey(value=>value+1)}catch(error){setError(error instanceof AppApiError?error.message:`Não foi possível ${action} o imóvel.`)}finally{setBusy(false)}}
  return <>
    <section className="app-page-heading"><div><span className="app-section-eyebrow">Portfólio</span><h1>Catálogo de imóveis</h1><p>Centralize os imóveis, pendências e vínculos da operação.</p></div>{canCreate&&<a className="app-primary-button" href="/app/imovel/">+ Novo imóvel</a>}</section>
    {error&&<div className="app-inline-error">{error}</div>}{notice&&<div className="app-inline-success">{notice}</div>}
    <section className="app-metrics app-metrics--compact">{[["Ativos",result?.active??0],["Rascunhos",result?.drafts??0],["Pendentes",result?.pending??0],["Publicados",result?.published??0],["Indisponíveis",result?.unavailable??0]].map(([label,value])=><article className="app-metric-card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className="app-filter-panel"><div className="app-search-field"><SearchIcon/><input placeholder="Título, código, endereço, proprietário, corretor ou referência..." value={search} onChange={event=>setSearch(event.target.value)}/></div><select value={status} onChange={event=>setStatus(event.target.value as PropertyStatus|"")}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={purpose} onChange={event=>setPurpose(event.target.value as PropertyPurpose|"")}><option value="">Todas as finalidades</option>{Object.entries(purposeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={type} onChange={event=>setType(event.target.value as PropertyType|"")}><option value="">Todos os tipos</option>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={archived} onChange={event=>{setArchived(event.target.value as "exclude"|"only");setSelectedId("")}}><option value="exclude">Imóveis ativos</option><option value="only">Imóveis arquivados</option></select></section>
    {canUpdate&&Boolean(result?.items.length)&&<section className="app-filter-panel"><select aria-label="Imóvel para alterar situação" value={selectedId} onChange={event=>setSelectedId(event.target.value)}><option value="">Selecione um imóvel</option>{result?.items.map(item=><option key={item.id} value={item.id}>{item.internalCode} — {item.title}</option>)}</select><button className="app-secondary-button" type="button" disabled={!selectedId||busy} onClick={()=>void changeLifecycle()}>{busy?"Salvando...":archived==="only"?"Restaurar imóvel":"Arquivar imóvel"}</button></section>}
    <section className="app-data-card">{loading?<div className="app-table-empty"><span className="app-spinner"/>Carregando imóveis...</div>:!result?.items.length?<div className="app-table-empty"><BuildingIcon/><h2>{archived==="only"?"Nenhum imóvel arquivado":"Nenhum imóvel encontrado"}</h2><p>{archived==="only"?"Os imóveis arquivados aparecerão aqui.":"Cadastre um imóvel ou ajuste os filtros."}</p>{canCreate&&archived==="exclude"&&<a className="app-primary-button" href="/app/imovel/">Cadastrar primeiro imóvel</a>}</div>:<div className="app-property-table app-property-table--actions"><header><span>Imóvel</span><span>Proprietário</span><span>Localização</span><span>Finalidade</span><span>Valor</span><span>Status</span><span>Ações</span></header>{result.items.map(item=><div className="app-property-table__row" key={item.id}><span><strong>{item.title}</strong><small>{item.internalCode}{item.pending.length?" · "+item.pending.length+" pendência(s)":""}{item.archivedAt?" · Arquivado":""}</small></span><span>{item.owners.map(owner=>owner.name).join(", ")||"—"}</span><span>{[item.neighborhood,item.city,item.state].filter(Boolean).join(" · ")||"—"}</span><span>{purposeLabels[item.purpose]} · {typeLabels[item.type]}</span><span>{item.purpose==="rent"?money(item.rentPrice):money(item.salePrice??item.rentPrice)}</span><span><em className={"app-status-pill "+(item.archivedAt?"status-inactive":"status-"+item.status)}>{item.archivedAt?"Arquivado":statusLabels[item.status]}</em></span><span className="app-row-actions">{!item.archivedAt&&<a className="app-secondary-button" href={"/app/imovel/?id="+encodeURIComponent(item.id)}>Editar</a>}{canUpdate&&<button className={"app-secondary-button"+(item.archivedAt?"":" is-danger")} type="button" disabled={busy} onClick={()=>void changeItemLifecycle(item.id,item.title,Boolean(item.archivedAt))}>{item.archivedAt?"Restaurar":"Excluir"}</button>}</span></div>)}</div>}</section>
  </>
}
