import { useEffect, useMemo, useState } from "react";
import { BuildingIcon, SearchIcon } from "../icons";
import { AppApiError } from "../../services/appApi";
import { listProperties, type PropertyListResult, type PropertyPurpose, type PropertyStatus, type PropertyType } from "../../services/propertiesApi";
interface Props{organizationId:string;canCreate:boolean}
const statusLabels:Record<PropertyStatus,string>={draft:"Rascunho",registering:"Em cadastro",awaiting_documents:"Aguardando documentos",evaluation:"Em avaliação",active:"Ativo",reserved:"Reservado",sold:"Vendido",rented:"Alugado",suspended:"Suspenso",inactive:"Inativo"};
const purposeLabels:Record<PropertyPurpose,string>={sale:"Venda",rent:"Aluguel",sale_rent:"Venda ou aluguel"};
const typeLabels:Record<PropertyType,string>={apartment:"Apartamento",house:"Casa",commercial:"Comercial",land:"Terreno",rural:"Rural",warehouse:"Galpão",building:"Prédio",room:"Sala",other:"Outro"};
function money(v:string|null){if(!v)return"—";return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(v))}
export function PropertiesPage({organizationId,canCreate}:Props){const[search,setSearch]=useState("");const[status,setStatus]=useState<PropertyStatus|"">("");const[purpose,setPurpose]=useState<PropertyPurpose|"">("");const[type,setType]=useState<PropertyType|"">("");const[result,setResult]=useState<PropertyListResult|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const query=useMemo(()=>({search:search.trim()||undefined,status:status||undefined,purpose:purpose||undefined,type:type||undefined,pageSize:50}),[search,status,purpose,type]);useEffect(()=>{const h=globalThis.setTimeout(()=>{setLoading(true);setError(null);void listProperties(organizationId,query).then(setResult).catch(e=>setError(e instanceof AppApiError?e.message:"Não foi possível carregar o catálogo.")).finally(()=>setLoading(false))},250);return()=>globalThis.clearTimeout(h)},[organizationId,query]);return <>
<section className="app-page-heading"><div><span className="app-section-eyebrow">Portfólio</span><h1>Catálogo de imóveis</h1><p>Centralize os imóveis, pendências e vínculos da operação.</p></div>{canCreate&&<a className="app-primary-button" href="/app/imovel/">+ Novo imóvel</a>}</section>
{error&&<div className="app-inline-error">{error}</div>}
<section className="app-metrics app-metrics--compact">{[["Ativos",result?.active??0],["Rascunhos",result?.drafts??0],["Pendentes",result?.pending??0],["Publicados",result?.published??0],["Indisponíveis",result?.unavailable??0]].map(([label,value])=><article className="app-metric-card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
<section className="app-filter-panel"><div className="app-search-field"><SearchIcon/><input placeholder="Título, código, endereço, proprietário, corretor ou referência..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value as PropertyStatus|"")}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={purpose} onChange={e=>setPurpose(e.target.value as PropertyPurpose|"")}><option value="">Todas as finalidades</option>{Object.entries(purposeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={type} onChange={e=>setType(e.target.value as PropertyType|"")}><option value="">Todos os tipos</option>{Object.entries(typeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></section>
<section className="app-data-card">{loading?<div className="app-table-empty"><span className="app-spinner"/>Carregando imóveis...</div>:!result?.items.length?<div className="app-table-empty"><BuildingIcon/><h2>Nenhum imóvel encontrado</h2><p>Cadastre um imóvel ou ajuste os filtros.</p>{canCreate&&<a className="app-primary-button" href="/app/imovel/">Cadastrar primeiro imóvel</a>}</div>:<div className="app-property-table"><header><span>Imóvel</span><span>Proprietário</span><span>Localização</span><span>Finalidade</span><span>Valor</span><span>Status</span></header>{result.items.map(item=><a key={item.id} href={`/app/imovel/?id=${encodeURIComponent(item.id)}`}><span><strong>{item.title}</strong><small>{item.internalCode}{item.pending.length?` · ${item.pending.length} pendência(s)`:""}</small></span><span>{item.owners.map(o=>o.name).join(", ")||"—"}</span><span>{[item.neighborhood,item.city,item.state].filter(Boolean).join(" · ")||"—"}</span><span>{purposeLabels[item.purpose]} · {typeLabels[item.type]}</span><span>{item.purpose==="rent"?money(item.rentPrice):money(item.salePrice??item.rentPrice)}</span><span><em className={`app-status-pill status-${item.status}`}>{statusLabels[item.status]}</em></span></a>)}</div>}</section>
</>}
