import { ensureValidAuthSession } from "../auth/session";
import type { LandingPageDocument, LandingSection, LandingTheme, LandingSeo } from "../landing-pages/model";
import { AppApiError } from "./appApi";

const apiBase=()=>{const value=import.meta.env.VITE_API_URL?.trim();if(!value)throw new AppApiError("A plataforma ainda não está conectada à API.","API_NOT_CONFIGURED");return value.replace(/\/+$/u,"")};
async function tenantRequest<T>(organizationId:string,path:string,init:RequestInit={}):Promise<T>{const session=await ensureValidAuthSession();if(!session)throw new AppApiError("Sua sessão expirou.","UNAUTHORIZED",401);const response=await fetch(`${apiBase()}${path}`,{...init,headers:{authorization:`Bearer ${session.accessToken}`,"x-organization-id":organizationId,...(init.body?{"content-type":"application/json"}:{}),...(init.headers||{})}});const body=await response.json().catch(()=>null) as {success?:boolean;data?:T;error?:{code?:string;message?:string}}|null;if(!response.ok||body?.success!==true||body.data===undefined)throw new AppApiError(body?.error?.message||"Não foi possível concluir a operação.",body?.error?.code||"API_ERROR",response.status);return body.data;}

export interface LandingPageSummary { id:string; name:string; slug:string; status:"draft"|"published"|"unpublished"; templateId:string; updatedAt:string; publishedAt:string|null; }
export const listLandingPages=(organizationId:string)=>tenantRequest<LandingPageSummary[]>(organizationId,"/portfolio/landing-pages");
export const createLandingPage=(organizationId:string,input:{name:string;templateId:string})=>tenantRequest<LandingPageDocument>(organizationId,"/portfolio/landing-pages",{method:"POST",body:JSON.stringify(input)});
export const getLandingPage=(organizationId:string,id:string)=>tenantRequest<LandingPageDocument>(organizationId,`/portfolio/landing-pages/${encodeURIComponent(id)}`);
export const updateLandingPage=(organizationId:string,id:string,input:{name:string;theme:LandingTheme;seo:LandingSeo;sections:LandingSection[];propertyIds:string[]})=>tenantRequest<LandingPageDocument>(organizationId,`/portfolio/landing-pages/${encodeURIComponent(id)}`,{method:"PUT",body:JSON.stringify(input)});
export const setLandingPageStatus=(organizationId:string,id:string,status:"published"|"unpublished")=>tenantRequest<LandingPageDocument>(organizationId,`/portfolio/landing-pages/${encodeURIComponent(id)}/${status==="published"?"publish":"unpublish"}`,{method:"POST"});

interface LandingImageUploadReady { storageKey:string; uploadUrl:string; requiredHeaders:Record<string,string>; }
export interface LandingImageUploadConfirmed { storageKey:string; imageUrl:string; }
export async function uploadLandingPageImage(organizationId:string,id:string,file:File):Promise<LandingImageUploadConfirmed>{const ready=await tenantRequest<LandingImageUploadReady>(organizationId,`/portfolio/landing-pages/${encodeURIComponent(id)}/images/upload-url`,{method:"POST",body:JSON.stringify({contentType:file.type,sizeBytes:file.size})});const upload=await fetch(ready.uploadUrl,{method:"PUT",headers:ready.requiredHeaders,body:file});if(!upload.ok)throw new AppApiError("Não foi possível enviar a imagem.","IMAGE_UPLOAD_FAILED",upload.status);return tenantRequest<LandingImageUploadConfirmed>(organizationId,`/portfolio/landing-pages/${encodeURIComponent(id)}/images/confirm`,{method:"POST",body:JSON.stringify({storageKey:ready.storageKey,contentType:file.type,sizeBytes:file.size})});}

export async function getPublicLandingPage(slug:string):Promise<LandingPageDocument>{const response=await fetch(`${apiBase()}/public/imob/${encodeURIComponent(slug)}`);const body=await response.json().catch(()=>null) as {success?:boolean;data?:LandingPageDocument;error?:{message?:string}}|null;if(!response.ok||body?.success!==true||!body.data)throw new AppApiError(body?.error?.message||"Página não encontrada.","PUBLIC_LANDING_NOT_FOUND",response.status);return body.data;}
export async function submitPublicLandingLead(slug:string,input:Record<string,string>):Promise<void>{const response=await fetch(`${apiBase()}/public/imob/${encodeURIComponent(slug)}/leads`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});if(!response.ok)throw new AppApiError("Não foi possível enviar sua mensagem.","PUBLIC_LEAD_ERROR",response.status);}
