import { ensureValidAuthSession } from "../auth/session";
import { AppApiError } from "./appApi";
const REQUEST_TIMEOUT_MS=15_000;
function apiBase(){const v=import.meta.env.VITE_API_URL?.trim();if(!v)throw new AppApiError("A plataforma ainda não está conectada à API.","API_NOT_CONFIGURED");return v.replace(/\/+$/u,"");}
async function tenantRequest<T>(organizationId:string,path:string,init:RequestInit={}):Promise<T>{const session=await ensureValidAuthSession();if(!session)throw new AppApiError("Sua sessão expirou. Entre novamente.","UNAUTHORIZED",401);const c=new AbortController(),t=globalThis.setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{const response=await fetch(`${apiBase()}${path}`,{...init,headers:{authorization:`Bearer ${session.accessToken}`,"x-organization-id":organizationId,...(init.body?{"content-type":"application/json"}:{}),...(init.headers??{})},signal:c.signal});let payload:unknown=null;try{payload=await response.json()}catch{payload=null}const body=payload as {success?:boolean;data?:T;error?:{code?:string;message?:string}}|null;if(!response.ok)throw new AppApiError(body?.error?.message||"Não foi possível concluir a operação.",body?.error?.code||"API_ERROR",response.status);if(body?.success!==true||body.data===undefined)throw new AppApiError("Recebemos uma resposta inesperada da plataforma.","INVALID_API_RESPONSE",response.status);return body.data}catch(error){if(error instanceof AppApiError)throw error;if(error instanceof DOMException&&error.name==="AbortError")throw new AppApiError("A plataforma demorou mais que o esperado para responder.","REQUEST_TIMEOUT");throw new AppApiError("Não foi possível conectar à plataforma. Verifique sua conexão e tente novamente.","NETWORK_ERROR")}finally{globalThis.clearTimeout(t)}}
export type PropertyStatus="draft"|"registering"|"awaiting_documents"|"evaluation"|"active"|"reserved"|"sold"|"rented"|"suspended"|"inactive";
export type PropertyPurpose="sale"|"rent"|"sale_rent";export type PropertyType="apartment"|"house"|"commercial"|"land"|"rural"|"warehouse"|"building"|"room"|"other";export type PropertyAreaUnit="m2"|"ha";
export interface PropertySettings{propertyTypes:Array<{code:PropertyType;label:string;enabled:boolean}>;amenities:string[];condominiumAmenities:string[];defaultPurpose:PropertyPurpose;defaultAreaUnit:PropertyAreaUnit;requireRegistryOnActive:boolean;requireDocumentationOnActive:boolean;requireSiteTitleOnActive:boolean}
export interface PropertyOwnerInput{contactId:string;ownershipPercentage:string|null;primary:boolean}
export interface PropertyFields{externalReference:string|null;title:string;type:PropertyType;purpose:PropertyPurpose;situation:string|null;status:PropertyStatus;responsibleMembershipId:string|null;sourceOpportunityId:string|null;postalCode:string|null;street:string|null;number:string|null;complement:string|null;neighborhood:string|null;city:string|null;state:string|null;latitude:string|null;longitude:string|null;publicLocation:string|null;salePrice:string|null;rentPrice:string|null;condominiumFee:string|null;iptuAnnual:string|null;otherFees:string|null;priceNotes:string|null;totalArea:string|null;usefulArea:string|null;landArea:string|null;builtArea:string|null;areaUnit:string;bedrooms:number|null;suites:number|null;bathrooms:number|null;toilets:number|null;parkingSpaces:number|null;amenities:string[];condominiumAmenities:string[];description:string|null;internalNotes:string|null;registryNumber:string|null;registryOffice:string|null;captureDate:string|null;authorizationStartsAt:string|null;authorizationEndsAt:string|null;commissionPercent:string|null;exclusive:boolean;financed:boolean;paidOff:boolean;documentationOk:boolean;authorizationNotes:string|null;siteTitle:string|null;siteDescription:string|null;siteLocationText:string|null;siteAddressVisibility:"hidden"|"neighborhood"|"street"|"full";owners:PropertyOwnerInput[]}
export interface PropertyListItem{id:string;internalCode:string;title:string;type:PropertyType;purpose:PropertyPurpose;status:PropertyStatus;published:boolean;city:string|null;state:string|null;neighborhood:string|null;salePrice:string|null;rentPrice:string|null;responsible:{membershipId:string;displayName:string}|null;owners:Array<{id:string;name:string}>;pending:string[];createdAt:string;updatedAt:string}
export interface PropertyListResult{total:number;active:number;drafts:number;pending:number;published:number;unavailable:number;items:PropertyListItem[];page:number;pageSize:number;totalItems:number;totalPages:number}
export interface PropertyOwnerRecord extends PropertyOwnerInput{name:string;email:string|null;phone:string|null}
export interface PropertyDetail extends Omit<PropertyFields,"owners">{id:string;internalCode:string;published:boolean;responsible:{membershipId:string;displayName:string}|null;owners:PropertyOwnerRecord[];sourceOpportunity:{id:string;title:string;contactId:string;contactName:string}|null;pending:string[];createdAt:string;updatedAt:string;timeline:Array<{id:string;eventType:string;actor:{userId:string;displayName:string}|null;data:Record<string,unknown>;createdAt:string}>}
export interface PropertyOptions{assignees:Array<{membershipId:string;displayName:string;email:string}>;contacts:Array<{id:string;name:string;email:string|null;phone:string|null;profiles:string[]}>;captureOpportunities:Array<{id:string;title:string;contactId:string;contactName:string;stageName:string;existingPropertyId:string|null}>;settings:PropertySettings}
export async function listProperties(organizationId:string,filters:{search?:string;status?:PropertyStatus;purpose?:PropertyPurpose;type?:PropertyType;city?:string;view?:"all"|"mine";sourceOpportunityId?:string;page?:number;pageSize?:number}={}):Promise<PropertyListResult>{const q=new URLSearchParams();for(const [k,v] of Object.entries(filters))if(v!==undefined&&v!==""&&v!==null)q.set(k,String(v));return tenantRequest(organizationId,`/portfolio/properties${q.size?`?${q}`:""}`)}
export async function getPropertyOptions(organizationId:string):Promise<PropertyOptions>{return tenantRequest(organizationId,"/portfolio/properties/options")}
export async function getProperty(organizationId:string,id:string):Promise<PropertyDetail>{return tenantRequest(organizationId,`/portfolio/properties/${encodeURIComponent(id)}`)}
export async function createProperty(organizationId:string,input:PropertyFields):Promise<PropertyDetail>{return tenantRequest(organizationId,"/portfolio/properties",{method:"POST",body:JSON.stringify(input)})}
export async function updateProperty(organizationId:string,id:string,input:PropertyFields):Promise<PropertyDetail>{return tenantRequest(organizationId,`/portfolio/properties/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(input)})}

export type PropertyImageContentType="image/jpeg"|"image/png"|"image/webp";
export interface PropertyImageItem{id:string;originalName:string;contentType:PropertyImageContentType;sizeBytes:number;sortOrder:number;primary:boolean;viewUrl:string;viewUrlExpiresInSeconds:number;createdAt:string}
export interface PropertyImageUploadReady{imageId:string;uploadUrl:string;expiresInSeconds:number;requiredHeaders:{"content-type":PropertyImageContentType}}
export const PROPERTY_IMAGE_MAX_BYTES=12*1024*1024;
export const PROPERTY_IMAGE_MAX_COUNT=30;
export async function listPropertyImages(organizationId:string,propertyId:string):Promise<PropertyImageItem[]>{return tenantRequest(organizationId,`/portfolio/properties/${encodeURIComponent(propertyId)}/images`)}
export async function createPropertyImageUpload(organizationId:string,propertyId:string,file:File):Promise<PropertyImageUploadReady>{return tenantRequest(organizationId,`/portfolio/properties/${encodeURIComponent(propertyId)}/images/upload-url`,{method:"POST",body:JSON.stringify({originalName:file.name,contentType:file.type,sizeBytes:file.size})})}
export async function uploadPropertyImageFile(ready:PropertyImageUploadReady,file:File):Promise<void>{const controller=new AbortController(),timeout=globalThis.setTimeout(()=>controller.abort(),60_000);try{const response=await fetch(ready.uploadUrl,{method:"PUT",headers:{"content-type":ready.requiredHeaders["content-type"]},body:file,signal:controller.signal});if(!response.ok)throw new AppApiError("Não foi possível enviar a imagem para o armazenamento.","IMAGE_UPLOAD_FAILED",response.status)}catch(error){if(error instanceof AppApiError)throw error;if(error instanceof DOMException&&error.name==="AbortError")throw new AppApiError("O envio da imagem demorou mais que o esperado.","IMAGE_UPLOAD_TIMEOUT");throw new AppApiError("Não foi possível enviar a imagem. Verifique sua conexão.","IMAGE_UPLOAD_NETWORK_ERROR")}finally{globalThis.clearTimeout(timeout)}}
export async function confirmPropertyImage(organizationId:string,propertyId:string,ready:PropertyImageUploadReady,file:File):Promise<PropertyImageItem[]>{return tenantRequest(organizationId,`/portfolio/properties/${encodeURIComponent(propertyId)}/images/confirm`,{method:"POST",body:JSON.stringify({imageId:ready.imageId,originalName:file.name,contentType:file.type,sizeBytes:file.size})})}
export async function setPropertyPrimaryImage(organizationId:string,propertyId:string,imageId:string):Promise<PropertyImageItem[]>{return tenantRequest(organizationId,`/portfolio/properties/${encodeURIComponent(propertyId)}/images/${encodeURIComponent(imageId)}/primary`,{method:"PATCH"})}
export async function reorderPropertyImages(organizationId:string,propertyId:string,imageIds:string[]):Promise<PropertyImageItem[]>{return tenantRequest(organizationId,`/portfolio/properties/${encodeURIComponent(propertyId)}/images/order`,{method:"PATCH",body:JSON.stringify({imageIds})})}
export async function deletePropertyImage(organizationId:string,propertyId:string,imageId:string):Promise<PropertyImageItem[]>{return tenantRequest(organizationId,`/portfolio/properties/${encodeURIComponent(propertyId)}/images/${encodeURIComponent(imageId)}`,{method:"DELETE"})}
