import { ensureValidAuthSession } from "../auth/session";
import { AppApiError } from "./appApi";
const REQUEST_TIMEOUT_MS=15_000;
function apiBase(){const value=import.meta.env.VITE_API_URL?.trim();if(!value)throw new AppApiError("A plataforma ainda não está conectada à API.","API_NOT_CONFIGURED");return value.replace(/\/+$/u,"");}
async function tenantRequest<T>(organizationId:string,path:string,init:RequestInit={}):Promise<T>{const session=await ensureValidAuthSession();if(!session)throw new AppApiError("Sua sessão expirou. Entre novamente.","UNAUTHORIZED",401);const controller=new AbortController();const timeout=globalThis.setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const response=await fetch(`${apiBase()}${path}`,{...init,headers:{authorization:`Bearer ${session.accessToken}`,"x-organization-id":organizationId,...(init.body?{"content-type":"application/json"}:{}),...(init.headers??{})},signal:controller.signal});let payload:unknown=null;try{payload=await response.json();}catch{payload=null;}const body=payload as {success?:boolean;data?:T;error?:{code?:string;message?:string;issues?:Array<{label?:string;message?:string}>}}|null;if(!response.ok){const issueText=body?.error?.issues?.map(issue=>issue.label||issue.message).filter(Boolean).join(" ")||"";throw new AppApiError([body?.error?.message||"Não foi possível concluir a operação.",issueText].filter(Boolean).join(" "),body?.error?.code||"API_ERROR",response.status);}if(body?.success!==true||body.data===undefined)throw new AppApiError("Recebemos uma resposta inesperada da plataforma.","INVALID_API_RESPONSE",response.status);return body.data;}catch(error){if(error instanceof AppApiError)throw error;if(error instanceof DOMException&&error.name==="AbortError")throw new AppApiError("A plataforma demorou mais que o esperado para responder.","REQUEST_TIMEOUT");throw new AppApiError("Não foi possível conectar à plataforma. Verifique sua conexão e tente novamente.","NETWORK_ERROR");}finally{globalThis.clearTimeout(timeout);}}
export type PortfolioPublicationObjective="sell"|"rent"|"showcase"|"capture";
export type PortfolioPublicationChannel="instagram"|"facebook"|"whatsapp"|"other";
export type PortfolioPublicationFormat="feed"|"story"|"carousel"|"banner";
export type PortfolioPublicationStatus="draft"|"approved"|"scheduled"|"published"|"failed"|"canceled";
export interface PublicationReadinessIssue{code:string;label:string;severity:"blocker"|"warning"}
export interface PublicationReadiness{ready:boolean;blockers:PublicationReadinessIssue[];warnings:PublicationReadinessIssue[]}
export interface PublicationPropertyOption{id:string;internalCode:string;title:string;status:string;purpose:string;responsible:{membershipId:string;displayName:string}|null;readiness:PublicationReadiness;defaults:{objective:PortfolioPublicationObjective;title:string;caption:string;cta:string;hashtags:string[]}}
export interface PublicationFields{propertyId:string;objective:PortfolioPublicationObjective;channel:PortfolioPublicationChannel;format:PortfolioPublicationFormat;status:PortfolioPublicationStatus;title:string;caption:string;cta:string|null;hashtags:string[];campaignName:string|null;trackingLink:string|null;scheduledAt:string|null}
export interface PublicationListItem extends PublicationFields{id:string;property:{id:string;internalCode:string;title:string};responsible:{membershipId:string;displayName:string}|null;readiness:PublicationReadiness;snapshot:{propertyId:string;internalCode:string;title:string;publicTitle:string;description:string|null;location:string|null;type:string;purpose:string;salePrice:string|null;rentPrice:string|null;bedrooms:number|null;bathrooms:number|null;parkingSpaces:number|null;amenities:string[];imageIds:string[];primaryImageId:string|null;propertyUpdatedAt:string};approvedAt:string|null;publishedAt:string|null;canceledAt:string|null;failureMessage:string|null;createdBy:{userId:string;displayName:string}|null;createdAt:string;updatedAt:string}
export interface PublicationListResult{propertiesInMarketing:number;drafts:number;scheduled:number;publishedLast30Days:number;failed:number;items:PublicationListItem[];page:number;pageSize:number;totalItems:number;totalPages:number}
export interface PublicationOptions{properties:PublicationPropertyOption[]}
export async function listPublications(organizationId:string,filters:{search?:string;status?:PortfolioPublicationStatus;channel?:PortfolioPublicationChannel;propertyId?:string;page?:number;pageSize?:number}={}):Promise<PublicationListResult>{const query=new URLSearchParams();for(const[key,value]of Object.entries(filters))if(value!==undefined&&value!==""&&value!==null)query.set(key,String(value));return tenantRequest(organizationId,`/portfolio/publications${query.size?`?${query}`:""}`);}
export async function getPublicationOptions(organizationId:string):Promise<PublicationOptions>{return tenantRequest(organizationId,"/portfolio/publications/options");}
export async function createPublication(organizationId:string,fields:PublicationFields):Promise<PublicationListItem>{return tenantRequest(organizationId,"/portfolio/publications",{method:"POST",body:JSON.stringify(fields)});}
export async function updatePublication(organizationId:string,publicationId:string,fields:PublicationFields):Promise<PublicationListItem>{return tenantRequest(organizationId,`/portfolio/publications/${encodeURIComponent(publicationId)}`,{method:"PATCH",body:JSON.stringify(fields)});}
