import { useCallback, useEffect, useRef, useState, type ChangeEvent } from "react";
import { AppApiError } from "../../services/appApi";
import { PROPERTY_IMAGE_MAX_BYTES, PROPERTY_IMAGE_MAX_COUNT, confirmPropertyImage, createPropertyImageUpload, deletePropertyImage, listPropertyImages, reorderPropertyImages, setPropertyPrimaryImage, uploadPropertyImageFile, type PropertyImageItem } from "../../services/propertiesApi";
interface Props{organizationId:string;propertyId:string|null;canUpdate:boolean;onChanged?:()=>void}
const allowedTypes=new Set(["image/jpeg","image/png","image/webp"]);
function sizeLabel(bytes:number){if(bytes<1024*1024)return`${Math.max(1,Math.round(bytes/1024))} KB`;return`${(bytes/(1024*1024)).toFixed(1)} MB`}
export function PropertyImagesPanel({organizationId,propertyId,canUpdate,onChanged}:Props){const[items,setItems]=useState<PropertyImageItem[]>([]);const[loading,setLoading]=useState(Boolean(propertyId));const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[uploadText,setUploadText]=useState<string|null>(null);const inputRef=useRef<HTMLInputElement|null>(null);
const load=useCallback(async()=>{if(!propertyId){setItems([]);setLoading(false);return}setLoading(true);setError(null);try{setItems(await listPropertyImages(organizationId,propertyId))}catch(e){setError(e instanceof AppApiError?e.message:"Não foi possível carregar as imagens.")}finally{setLoading(false)}},[organizationId,propertyId]);useEffect(()=>{void load()},[load]);
async function chooseFiles(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files??[]);event.target.value="";if(!propertyId||!files.length||busy)return;const available=PROPERTY_IMAGE_MAX_COUNT-items.length;if(available<=0){setError(`Este imóvel já possui o limite de ${PROPERTY_IMAGE_MAX_COUNT} imagens.`);return}const selected=files.slice(0,available);const invalid=selected.find(file=>!allowedTypes.has(file.type)||file.size<=0||file.size>PROPERTY_IMAGE_MAX_BYTES);if(invalid){setError(`${invalid.name}: use JPG, PNG ou WEBP com até 12 MB.`);return}setBusy(true);setError(null);try{let latest=items;for(const[index,file]of selected.entries()){setUploadText(`Enviando ${index+1} de ${selected.length}: ${file.name}`);const ready=await createPropertyImageUpload(organizationId,propertyId,file);await uploadPropertyImageFile(ready,file);latest=await confirmPropertyImage(organizationId,propertyId,ready,file);setItems(latest)}onChanged?.()}catch(e){setError(e instanceof AppApiError?e.message:"Não foi possível enviar uma das imagens.");await load()}finally{setBusy(false);setUploadText(null)}}
async function makePrimary(imageId:string){if(!propertyId||busy)return;setBusy(true);setError(null);try{setItems(await setPropertyPrimaryImage(organizationId,propertyId,imageId));onChanged?.()}catch(e){setError(e instanceof AppApiError?e.message:"Não foi possível definir a foto principal.")}finally{setBusy(false)}}
async function move(index:number,direction:-1|1){if(!propertyId||busy)return;const target=index+direction;if(target<0||target>=items.length)return;const next=[...items];const moved=next[index];const other=next[target];if(!moved||!other)return;next[index]=other;next[target]=moved;setBusy(true);setError(null);try{setItems(await reorderPropertyImages(organizationId,propertyId,next.map(item=>item.id)));onChanged?.()}catch(e){setError(e instanceof AppApiError?e.message:"Não foi possível alterar a ordem das imagens.");await load()}finally{setBusy(false)}}
async function remove(image:PropertyImageItem){if(!propertyId||busy||!globalThis.confirm(`Remover a imagem “${image.originalName}”?`))return;setBusy(true);setError(null);try{setItems(await deletePropertyImage(organizationId,propertyId,image.id));onChanged?.()}catch(e){setError(e instanceof AppApiError?e.message:"Não foi possível remover a imagem.")}finally{setBusy(false)}}
if(!propertyId)return <div className="app-property-images-save-first"><strong>Salve o imóvel antes de enviar imagens.</strong><p>Depois do primeiro salvamento, esta aba libera a galeria privada.</p></div>;
return <div className="app-property-images-panel"><div className="app-property-images-toolbar"><div><h2>Galeria do imóvel</h2><p>JPG, PNG ou WEBP · até 12 MB por arquivo · máximo de {PROPERTY_IMAGE_MAX_COUNT} imagens.</p></div>{canUpdate&&<><input ref={inputRef} className="app-visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>void chooseFiles(e)}/><button type="button" className="app-primary-button" onClick={()=>inputRef.current?.click()} disabled={busy||items.length>=PROPERTY_IMAGE_MAX_COUNT}>+ Adicionar imagens</button></>}</div>{error&&<div className="app-inline-error">{error}</div>}{uploadText&&<div className="app-property-uploading"><span className="app-spinner"/>{uploadText}</div>}{loading?<div className="app-table-empty"><span className="app-spinner"/>Carregando imagens...</div>:items.length===0?<button type="button" className="app-property-image-drop" disabled={!canUpdate||busy} onClick={()=>inputRef.current?.click()}><strong>Nenhuma imagem adicionada</strong><span>Adicione fotos para completar o cadastro e definir a imagem principal.</span></button>:<div className="app-property-image-grid">{items.map((image,index)=><article key={image.id} className={image.primary?"is-primary":""}><div className="app-property-image-preview"><img src={image.viewUrl} alt={image.originalName}/>{image.primary&&<span className="app-property-primary-badge">Principal</span>}<span className="app-property-order-badge">{index+1}</span></div><div className="app-property-image-meta"><strong title={image.originalName}>{image.originalName}</strong><small>{sizeLabel(image.sizeBytes)}</small></div>{canUpdate&&<div className="app-property-image-actions"><button type="button" onClick={()=>void move(index,-1)} disabled={busy||index===0} title="Mover para a esquerda">←</button><button type="button" onClick={()=>void move(index,1)} disabled={busy||index===items.length-1} title="Mover para a direita">→</button>{!image.primary&&<button type="button" onClick={()=>void makePrimary(image.id)} disabled={busy}>Tornar principal</button>}<button type="button" className="is-danger" onClick={()=>void remove(image)} disabled={busy}>Remover</button></div>}</article>)}</div>}<p className="app-property-images-help">A primeira imagem é definida automaticamente como principal. A ordem acima será reutilizada na publicação e na futura galeria pública.</p></div>}
