import { Fragment, useEffect, useRef, type CSSProperties, type FormEvent, type PointerEvent as ReactPointerEvent } from "react";
import type { LandingPageDocument, LandingSection } from "./model";
import "./landingPage.css";
const text=(s:LandingSection,k:string,f="")=>typeof s.content[k]==="string"?s.content[k] as string:f;
const items=(s:LandingSection)=>Array.isArray(s.content.items)?s.content.items.filter((v):v is Record<string,unknown>=>Boolean(v)&&typeof v==="object"&&!Array.isArray(v)):[];
const records=(s:LandingSection,key:string)=>Array.isArray(s.content[key])?(s.content[key] as unknown[]).filter((v):v is Record<string,unknown>=>Boolean(v)&&typeof v==="object"&&!Array.isArray(v)):[];
const money=(v:string|null)=>v?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(v)):"Consulte";
function Navigation({page,section}:{page:LandingPageDocument;section:LandingSection}){return <header className="lp-navigation"><div className="lp-shell"><strong>{page.identity.logoUrl?<img src={page.identity.logoUrl} alt={page.identity.name}/>:page.identity.name}</strong><nav><a href={text(section,"propertiesLink","#imoveis")}>{text(section,"propertiesLabel","Imóveis")}</a><a href={text(section,"advertiseLink","#contato")}>{text(section,"advertiseLabel","Anunciar")}</a><a href={text(section,"aboutLink","#sobre")}>{text(section,"aboutLabel","Sobre mim")}</a><a className="lp-navigation__favorite" href="#imoveis" aria-label={text(section,"favoriteLabel","Favoritos")}>♥</a></nav></div></header>}
function RegionsCarousel({section}:{section:LandingSection}){
 const track=useRef<HTMLDivElement>(null),drag=useRef({active:false,x:0,left:0});
 const visible=items(section).filter(item=>item.visible!==false);
 const move=(direction:number)=>{const node=track.current;if(!node)return;const amount=Math.max(260,node.clientWidth*.72);const atEnd=node.scrollLeft+node.clientWidth>=node.scrollWidth-8;const atStart=node.scrollLeft<=8;node.scrollTo({left:direction>0&&atEnd?0:direction<0&&atStart?node.scrollWidth:node.scrollLeft+direction*amount,behavior:"smooth"});};
 useEffect(()=>{if(visible.length<2)return;const timer=window.setInterval(()=>move(1),4500);return()=>window.clearInterval(timer);},[visible.length]);
 const pointerDown=(event:ReactPointerEvent<HTMLDivElement>)=>{const node=track.current;if(!node)return;drag.current={active:true,x:event.clientX,left:node.scrollLeft};node.setPointerCapture(event.pointerId);};
 const pointerMove=(event:ReactPointerEvent<HTMLDivElement>)=>{if(!drag.current.active||!track.current)return;track.current.scrollLeft=drag.current.left-(event.clientX-drag.current.x);};
 const pointerUp=()=>{drag.current.active=false;};
 return <section id="regioes" className="lp-section lp-regions"><div className="lp-shell lp-regions__heading"><div><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p></div>{visible.length>1&&<div className="lp-regions__controls"><button type="button" onClick={()=>move(-1)} aria-label="Cidade anterior">‹</button><button type="button" onClick={()=>move(1)} aria-label="Próxima cidade">›</button></div>}</div><div ref={track} className="lp-regions__track" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}>{visible.map((item,index)=><article key={index} style={{backgroundImage:`linear-gradient(0deg,rgba(0,0,0,.68),transparent 65%),url(${String(item.imageUrl||"")})`}}><strong>{String(item.title||"")}</strong></article>)}</div></section>;
}
export function LandingPageRenderer({page,preview=false,onSubmit}:{page:LandingPageDocument;preview?:boolean;onSubmit?:(data:Record<string,string>)=>Promise<void>|void}){
 const style={"--lp-primary":page.theme.primaryColor,"--lp-secondary":page.theme.secondaryColor,"--lp-bg":page.theme.backgroundColor,"--lp-surface":page.theme.surfaceColor,"--lp-text":page.theme.textColor,"--lp-muted":page.theme.mutedTextColor,"--lp-button-text":page.theme.buttonTextColor,"--lp-border":page.theme.borderColor} as CSSProperties;
 const sections=page.sections.filter(s=>s.visible).sort((a,b)=>a.order-b.order),hasNavigation=sections.some(s=>s.type==="navigation"),hero=sections.find(s=>s.type==="hero");
 const fallbackNavigation:LandingSection={id:"navigation-fallback",type:"navigation",order:-1,visible:true,settings:{},content:{propertiesLabel:hero?text(hero,"navPropertiesLabel","Imóveis"):"Imóveis",advertiseLabel:"Anunciar",aboutLabel:hero?text(hero,"navAboutLabel","Sobre mim"):"Sobre mim"}};
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());if(String(data.website||""))return;void onSubmit?.(Object.fromEntries(Object.entries(data).map(([k,v])=>[k,String(v)])));event.currentTarget.reset();};
 return <main className={`lp ${preview?"lp--preview":""}`} style={style}>{!hasNavigation&&hero&&<Navigation page={page} section={fallbackNavigation}/>}
 {sections.map(section=>{
  if(section.type==="navigation")return <Navigation key={section.id} page={page} section={section}/>;
  if(section.type==="hero")return <section key={section.id} className="lp-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(7,9,18,.74),rgba(7,9,18,.12)),url(${text(section,"imageUrl")})`}}><div className="lp-shell lp-hero__body"><h1>{text(section,"title")}</h1><p>{text(section,"description")}</p><a className="lp-button" href={text(section,"buttonLink","#imoveis")}>{text(section,"buttonLabel","Ver imóveis")}</a></div><div className="lp-hero__stats"><span><b>{text(section,"marketYearsValue","+10 anos")}</b>{text(section,"marketYearsLabel","de mercado")}</span><span><b>{page.properties.length} imóveis</b>{text(section,"propertiesStatLabel","no portfólio")}</span><span><b>{page.identity.address||"Sua região"}</b>{text(section,"locationStatLabel","atuação especializada")}</span><span><b>{page.identity.creci||"CRECI 00000-F"}</b>{text(section,"credentialStatLabel","corretor credenciado")}</span></div></section>;
  if(section.type==="featured-properties"){const uploads=records(section,"images");const slots=Array.from({length:9},(_,index)=>({property:page.properties[index]??null,imageUrl:String(uploads[index]?.imageUrl||page.properties[index]?.imageUrl||""),visible:uploads[index]?.visible!==false})).filter(slot=>slot.visible);return <section key={section.id} id="imoveis" className="lp-section lp-shell"><header><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p></header><div className={`lp-properties lp-properties--count-${slots.length}`}>{slots.map(({property:p,imageUrl},index)=><article key={p?.id??`slot-${index}`} className={`${index===0&&slots.length>=3?"is-featured ":""}${p||imageUrl?"":"is-empty"}`}>{imageUrl?<img loading="lazy" src={imageUrl} alt={p?.title||`Imagem de imóvel ${index+1}`}/>:<div className="lp-image-placeholder"/>}<span className="lp-property-favorite">♡</span>{p&&<div><small>{p.location||"Localização sob consulta"}</small><h3>{p.title}</h3><p>{[p.suites&&`${p.suites} suítes`,p.parkingSpaces&&`${p.parkingSpaces} vagas`].filter(Boolean).join(" · ")}</p><strong>{money(p.salePrice||p.rentPrice)}</strong></div>}</article>)}</div></section>;}
  if(section.type==="about")return <section key={section.id} id="sobre" className="lp-about"><div className="lp-shell"><div className="lp-about__copy"><small>{text(section,"eyebrow")}</small><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p></div>{text(section,"imageUrl")&&<div className="lp-about__image"><img loading="lazy" src={text(section,"imageUrl")} alt={page.identity.name}/></div>}</div></section>;
  if(section.type==="services")return <section key={section.id} className="lp-section lp-shell lp-services"><h2>{text(section,"title")}</h2><div>{items(section).map((item,index)=><article key={index}><b>{String(index+1).padStart(2,"0")}</b><h3>{String(item.title||"")}</h3><p>{String(item.description||"")}</p></article>)}</div></section>;
  if(section.type==="regions")return <RegionsCarousel key={section.id} section={section}/>;
  if(section.type==="contact")return <section key={section.id} id="contato" className="lp-contact-section"><div className="lp-section lp-shell lp-contact"><header className="lp-contact__intro"><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p></header><address className="lp-contact__details">{page.identity.address&&<div className="lp-contact__detail"><span aria-hidden="true">⌖</span><p><small>{text(section,"officeLabel","Escritório")}</small>{page.identity.address}</p></div>}{(page.identity.whatsapp||page.identity.phone)&&<div className="lp-contact__detail"><span aria-hidden="true">◉</span><p><small>{text(section,"whatsappInfoLabel","WhatsApp")}</small><a href={`tel:${page.identity.whatsapp||page.identity.phone}`}>{page.identity.whatsapp||page.identity.phone}</a></p></div>}{page.identity.email&&<div className="lp-contact__detail"><span aria-hidden="true">✉</span><p><small>{text(section,"emailInfoLabel","E-mail")}</small><a href={`mailto:${page.identity.email}`}>{page.identity.email}</a></p></div>}{text(section,"websiteValue")&&<div className="lp-contact__detail"><span aria-hidden="true">◎</span><p><small>{text(section,"websiteLabel","Website")}</small>{text(section,"websiteValue")}</p></div>}{page.identity.creci&&<div className="lp-contact__detail"><span aria-hidden="true">▣</span><p><small>{text(section,"creciLabel","CRECI")}</small>{page.identity.creci}</p></div>}</address><form onSubmit={submit}><input className="lp-honeypot" name="website" tabIndex={-1}/><label>{text(section,"nameLabel","Nome completo")}<input required name="name" placeholder="Seu nome"/></label><label>{text(section,"whatsappLabel","WhatsApp")}<input required name="phone" placeholder="(00) 00000-0000"/></label><label className="is-wide">{text(section,"emailLabel","E-mail")}<input name="email" type="email" placeholder="seu@email.com"/></label><label className="is-wide">{text(section,"interestLabel","Interesse")}<select name="interest"><option value="">Selecione o tipo de imóvel</option><option value="buyer">{text(section,"buyerOptionLabel")}</option><option value="capture">{text(section,"captureOptionLabel")}</option></select></label><label className="is-wide">{text(section,"messageLabel","Mensagem")}<textarea required name="message" placeholder="Conte-nos sobre o que você busca..."/></label><button className="lp-button" type="submit">{text(section,"buttonLabel","Enviar mensagem")}</button></form></div></section>;
  if(section.type==="footer"){const navigation=records(section,"navigationItems"),regions=records(section,"regionItems");return <footer key={section.id} className="lp-footer"><div className="lp-shell"><div className="lp-footer__grid"><div className="lp-footer__brand"><strong>{page.identity.logoUrl?<img src={page.identity.logoUrl} alt={page.identity.name}/>:page.identity.name}</strong><p>{text(section,"description")}</p><div className="lp-footer__socials">{(text(section,"instagramUrl")||page.identity.instagramUrl)&&<a href={text(section,"instagramUrl")||page.identity.instagramUrl||"#"} aria-label="Instagram">◎</a>}{text(section,"tiktokUrl")&&<a href={text(section,"tiktokUrl")} aria-label="TikTok">♪</a>}{text(section,"youtubeUrl")&&<a href={text(section,"youtubeUrl")} aria-label="YouTube">▶</a>}</div></div><nav><strong>{text(section,"navigationTitle","Navegação")}</strong>{navigation.map((item,index)=><a key={index} href={String(item.link||"#")}>{String(item.title||"")}</a>)}</nav><nav><strong>{text(section,"regionsTitle","Regiões atendidas")}</strong>{regions.map((item,index)=><a key={index} href={String(item.link||"#regioes")}>{String(item.title||"")}</a>)}</nav></div><div className="lp-footer__bottom"><small>© {new Date().getFullYear()} {page.identity.name}. {text(section,"copyrightText","Todos os direitos reservados.")} · <a href={text(section,"privacyLink","#")}>{text(section,"privacyLabel","Política de Privacidade")}</a></small><span>{text(section,"developerLabel","Desenvolvido por")} <strong>escala imob</strong></span></div></div></footer>;}
  return <Fragment key={section.id}/>;
 })}</main>;
}
