import type { CSSProperties, FormEvent } from "react";
import type { LandingPageDocument, LandingSection } from "./model";
import "./landingPage.css";
const text=(section:LandingSection,key:string,fallback="")=>typeof section.content[key]==="string"?section.content[key] as string:fallback;
const items=(section:LandingSection)=>Array.isArray(section.content.items)?section.content.items.filter((item):item is Record<string,unknown>=>Boolean(item)&&typeof item==="object"&&!Array.isArray(item)):[];
const money=(value:string|null)=>value?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(value)):"Consulte";
export function LandingPageRenderer({page,preview=false,onSubmit}:{page:LandingPageDocument;preview?:boolean;onSubmit?:(data:Record<string,string>)=>Promise<void>|void}) {
 const style={"--lp-primary":page.theme.primaryColor,"--lp-secondary":page.theme.secondaryColor,"--lp-bg":page.theme.backgroundColor,"--lp-surface":page.theme.surfaceColor,"--lp-text":page.theme.textColor,"--lp-muted":page.theme.mutedTextColor,"--lp-button-text":page.theme.buttonTextColor,"--lp-border":page.theme.borderColor} as CSSProperties;
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());if(String(data.website||""))return;void onSubmit?.(Object.fromEntries(Object.entries(data).map(([k,v])=>[k,String(v)])));event.currentTarget.reset();};
 return <main className={`lp ${preview?"lp--preview":""}`} style={style}>{page.sections.filter(s=>s.visible).sort((a,b)=>a.order-b.order).map(section=>{
  if(section.type==="hero") return <section key={section.id} className="lp-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(7,9,18,.75),rgba(7,9,18,.16)),url(${text(section,"imageUrl")})`}}><nav><strong>{page.identity.logoUrl?<img src={page.identity.logoUrl} alt={page.identity.name}/>:page.identity.name}</strong><div><a href="#imoveis">{text(section,"navPropertiesLabel","Imóveis")}</a><a href="#sobre">{text(section,"navAboutLabel","Sobre mim")}</a><a href="#contato">{text(section,"navContactLabel","Contato")}</a></div></nav><div className="lp-shell lp-hero__body"><h1>{text(section,"title")}</h1><p>{text(section,"description")}</p><a className="lp-button" href={text(section,"buttonLink","#imoveis")}>{text(section,"buttonLabel","Ver imóveis")}</a></div><div className="lp-hero__stats"><span><b>{page.properties.length}</b> {text(section,"propertiesStatLabel","imóveis selecionados")}</span><span><b>{page.identity.creci||"CRECI"}</b> {text(section,"credentialStatLabel","credenciamento")}</span><span><b>{page.identity.address||"Atendimento regional"}</b> {text(section,"locationStatLabel","localização")}</span></div></section>;
  if(section.type==="featured-properties") return <section key={section.id} id="imoveis" className="lp-section lp-shell"><header><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p></header><div className="lp-properties">{page.properties.map((p,index)=><article key={p.id} className={index===0?"is-featured":""}>{p.imageUrl?<img loading="lazy" src={p.imageUrl} alt={p.title}/>:<div className="lp-image-placeholder"/>}<div><small>{p.location||"Localização sob consulta"}</small><h3>{p.title}</h3><p>{[p.suites&&`${p.suites} suítes`,p.parkingSpaces&&`${p.parkingSpaces} vagas`].filter(Boolean).join(" · ")}</p><strong>{money(p.salePrice||p.rentPrice)}</strong></div></article>)}</div></section>;
  if(section.type==="about") return <section key={section.id} id="sobre" className="lp-about"><div className="lp-shell"><div><small>{text(section,"eyebrow")}</small><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p></div>{text(section,"imageUrl")&&<img loading="lazy" src={text(section,"imageUrl")} alt={page.identity.name}/>}</div></section>;
  if(section.type==="services") return <section key={section.id} className="lp-section lp-shell lp-services"><h2>{text(section,"title")}</h2><div>{items(section).map((item,index)=><article key={index}><b>{String(index+1).padStart(2,"0")}</b><h3>{String(item.title||"")}</h3><p>{String(item.description||"")}</p></article>)}</div></section>;
  if(section.type==="regions") return <section key={section.id} className="lp-section lp-regions"><div className="lp-shell"><h2>{text(section,"title")}</h2></div><div>{items(section).map((item,index)=><article key={index} style={{backgroundImage:`linear-gradient(0deg,rgba(0,0,0,.65),transparent),url(${String(item.imageUrl||"")})`}}><strong>{String(item.title||"")}</strong></article>)}</div></section>;
  if(section.type==="contact") return <section key={section.id} id="contato" className="lp-section lp-shell lp-contact"><div><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p><address>{page.identity.email&&<a href={`mailto:${page.identity.email}`}>{page.identity.email}</a>}{page.identity.phone&&<a href={`tel:${page.identity.phone}`}>{page.identity.phone}</a>}{page.identity.whatsapp&&<a href={`https://wa.me/55${page.identity.whatsapp}`}>{text(section,"whatsappLabel","WhatsApp")}</a>}</address></div><form onSubmit={submit}><input className="lp-honeypot" name="website" tabIndex={-1} autoComplete="off"/><label>{text(section,"nameLabel","Nome completo")}<input required name="name" maxLength={160}/></label><label>{text(section,"whatsappLabel","WhatsApp")}<input required name="phone" inputMode="tel" maxLength={24}/></label><label>{text(section,"emailLabel","E-mail")}<input name="email" type="email" maxLength={320}/></label><label>{text(section,"interestLabel","Interesse")}<select name="interest"><option value="buyer">{text(section,"buyerOptionLabel","Comprar ou alugar")}</option><option value="capture">{text(section,"captureOptionLabel","Anunciar meu imóvel")}</option></select></label><label className="is-wide">{text(section,"messageLabel","Mensagem")}<textarea required name="message" maxLength={2000}/></label><button className="lp-button" type="submit">{text(section,"buttonLabel","Enviar mensagem")}</button></form></section>;
  if(section.type==="footer") return <footer key={section.id} className="lp-footer"><div className="lp-shell"><strong>{page.identity.name}</strong><p>{text(section,"description")}</p><small>© {new Date().getFullYear()} {page.identity.name}. {text(section,"copyrightText","Todos os direitos reservados.")}</small></div></footer>;
  return null;
 })}</main>;
}
