import { Fragment, type CSSProperties, type FormEvent } from "react";
import type { LandingPageDocument, LandingSection } from "./model";
import "./landingPage.css";
const text=(s:LandingSection,k:string,f="")=>typeof s.content[k]==="string"?s.content[k] as string:f;
const items=(s:LandingSection)=>Array.isArray(s.content.items)?s.content.items.filter((v):v is Record<string,unknown>=>Boolean(v)&&typeof v==="object"&&!Array.isArray(v)):[];
const money=(v:string|null)=>v?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(v)):"Consulte";
function Navigation({page,section}:{page:LandingPageDocument;section:LandingSection}){return <header className="lp-navigation"><div className="lp-shell"><strong>{page.identity.logoUrl?<img src={page.identity.logoUrl} alt={page.identity.name}/>:page.identity.name}</strong><nav><a href={text(section,"propertiesLink","#imoveis")}>{text(section,"propertiesLabel","Imóveis")}</a><a href={text(section,"advertiseLink","#contato")}>{text(section,"advertiseLabel","Anunciar")}</a><a href={text(section,"aboutLink","#sobre")}>{text(section,"aboutLabel","Sobre mim")}</a><a className="lp-navigation__favorite" href="#imoveis" aria-label={text(section,"favoriteLabel","Favoritos")}>♥</a></nav></div></header>}
export function LandingPageRenderer({page,preview=false,onSubmit}:{page:LandingPageDocument;preview?:boolean;onSubmit?:(data:Record<string,string>)=>Promise<void>|void}){
 const style={"--lp-primary":page.theme.primaryColor,"--lp-secondary":page.theme.secondaryColor,"--lp-bg":page.theme.backgroundColor,"--lp-surface":page.theme.surfaceColor,"--lp-text":page.theme.textColor,"--lp-muted":page.theme.mutedTextColor,"--lp-button-text":page.theme.buttonTextColor,"--lp-border":page.theme.borderColor} as CSSProperties;
 const sections=page.sections.filter(s=>s.visible).sort((a,b)=>a.order-b.order),hasNavigation=sections.some(s=>s.type==="navigation"),hero=sections.find(s=>s.type==="hero");
 const fallbackNavigation:LandingSection={id:"navigation-fallback",type:"navigation",order:-1,visible:true,settings:{},content:{propertiesLabel:hero?text(hero,"navPropertiesLabel","Imóveis"):"Imóveis",advertiseLabel:"Anunciar",aboutLabel:hero?text(hero,"navAboutLabel","Sobre mim"):"Sobre mim"}};
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());if(String(data.website||""))return;void onSubmit?.(Object.fromEntries(Object.entries(data).map(([k,v])=>[k,String(v)])));event.currentTarget.reset();};
 return <main className={`lp ${preview?"lp--preview":""}`} style={style}>{!hasNavigation&&hero&&<Navigation page={page} section={fallbackNavigation}/>}
 {sections.map(section=>{
  if(section.type==="navigation")return <Navigation key={section.id} page={page} section={section}/>;
  if(section.type==="hero")return <section key={section.id} className="lp-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(7,9,18,.74),rgba(7,9,18,.12)),url(${text(section,"imageUrl")})`}}><div className="lp-shell lp-hero__body"><h1>{text(section,"title")}</h1><p>{text(section,"description")}</p><a className="lp-button" href={text(section,"buttonLink","#imoveis")}>{text(section,"buttonLabel","Ver imóveis")}</a></div><div className="lp-hero__stats"><span><b>{text(section,"marketYearsValue","+10 anos")}</b>{text(section,"marketYearsLabel","de mercado")}</span><span><b>{page.properties.length} imóveis</b>{text(section,"propertiesStatLabel","no portfólio")}</span><span><b>{page.identity.address||"Sua região"}</b>{text(section,"locationStatLabel","atuação especializada")}</span><span><b>{page.identity.creci||"CRECI 00000-F"}</b>{text(section,"credentialStatLabel","corretor credenciado")}</span></div></section>;
  if(section.type==="featured-properties"){const slots=Array.from({length:9},(_,index)=>page.properties[index]??null);return <section key={section.id} id="imoveis" className="lp-section lp-shell"><header><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p></header><div className="lp-properties">{slots.map((p,index)=><article key={p?.id??`slot-${index}`} className={`${index===0?"is-featured ":""}${p?"":"is-empty"}`}>{p?.imageUrl?<img loading="lazy" src={p.imageUrl} alt={p.title}/>:<div className="lp-image-placeholder"/>}<span className="lp-property-favorite">♡</span>{p&&<div><small>{p.location||"Localização sob consulta"}</small><h3>{p.title}</h3><p>{[p.suites&&`${p.suites} suítes`,p.parkingSpaces&&`${p.parkingSpaces} vagas`].filter(Boolean).join(" · ")}</p><strong>{money(p.salePrice||p.rentPrice)}</strong></div>}</article>)}</div></section>;}
  if(section.type==="about")return <section key={section.id} id="sobre" className="lp-about"><div className="lp-shell"><div className="lp-about__copy"><small>{text(section,"eyebrow")}</small><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p></div>{text(section,"imageUrl")&&<div className="lp-about__image"><img loading="lazy" src={text(section,"imageUrl")} alt={page.identity.name}/></div>}</div></section>;
  if(section.type==="services")return <section key={section.id} className="lp-section lp-shell lp-services"><h2>{text(section,"title")}</h2><div>{items(section).map((item,index)=><article key={index}><b>{String(index+1).padStart(2,"0")}</b><h3>{String(item.title||"")}</h3><p>{String(item.description||"")}</p></article>)}</div></section>;
  if(section.type==="regions")return <section key={section.id} className="lp-section lp-regions"><div className="lp-shell"><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p></div><div className="lp-regions__track">{items(section).map((item,index)=><article key={index} style={{backgroundImage:`linear-gradient(0deg,rgba(0,0,0,.68),transparent 65%),url(${String(item.imageUrl||"")})`}}><strong>{String(item.title||"")}</strong></article>)}</div></section>;
  if(section.type==="contact")return <section key={section.id} id="contato" className="lp-section lp-shell lp-contact"><div><h2>{text(section,"title")}</h2><p>{text(section,"description")}</p><address>{page.identity.email&&<a href={`mailto:${page.identity.email}`}>{page.identity.email}</a>}{page.identity.phone&&<a href={`tel:${page.identity.phone}`}>{page.identity.phone}</a>}</address></div><form onSubmit={submit}><input className="lp-honeypot" name="website" tabIndex={-1}/><label>{text(section,"nameLabel","Nome completo")}<input required name="name"/></label><label>{text(section,"whatsappLabel","WhatsApp")}<input required name="phone"/></label><label>{text(section,"emailLabel","E-mail")}<input name="email" type="email"/></label><label>{text(section,"interestLabel","Interesse")}<select name="interest"><option value="buyer">{text(section,"buyerOptionLabel")}</option><option value="capture">{text(section,"captureOptionLabel")}</option></select></label><label className="is-wide">{text(section,"messageLabel","Mensagem")}<textarea required name="message"/></label><button className="lp-button" type="submit">{text(section,"buttonLabel","Enviar mensagem")}</button></form></section>;
  if(section.type==="footer")return <footer key={section.id} className="lp-footer"><div className="lp-shell"><strong>{page.identity.name}</strong><p>{text(section,"description")}</p><small>© {new Date().getFullYear()} {page.identity.name}. {text(section,"copyrightText","Todos os direitos reservados.")}</small></div></footer>;
  return <Fragment key={section.id}/>;
 })}</main>;
}
