export type LandingSectionType = "navigation" | "hero" | "featured-properties" | "about" | "services" | "regions" | "contact" | "footer" | "custom";
export type LandingStatus = "draft" | "published" | "unpublished";
export interface LandingCatalogSettings { title: string; description: string; backLabel: string; breadcrumbHomeLabel: string; searchLabel: string; favoritesLabel: string; primaryColor: string; backgroundColor: string; surfaceColor: string; textColor: string; mutedTextColor: string; buttonTextColor: string; borderColor: string; }
export interface LandingPropertySettings { backLabel: string; breadcrumbHomeLabel: string; photosLabel: string; contactButtonLabel: string; saveLabel: string; savedLabel: string; shareLabel: string; aboutTitle: string; featuresTitle: string; valuationTitle: string; proximityTitle: string; nearbyTitle: string; similarTitle: string; similarActionLabel: string; primaryColor: string; backgroundColor: string; surfaceColor: string; textColor: string; mutedTextColor: string; buttonTextColor: string; borderColor: string; }
export interface LandingTheme { primaryColor: string; secondaryColor: string; backgroundColor: string; surfaceColor: string; textColor: string; mutedTextColor: string; buttonTextColor: string; borderColor: string; catalog?: Partial<LandingCatalogSettings>; property?: Partial<LandingPropertySettings>; }
export interface LandingSeo { title: string; description: string; openGraphTitle: string; openGraphDescription: string; openGraphImage: string | null; }
export interface LandingSection { id: string; type: LandingSectionType; order: number; visible: boolean; content: Record<string, unknown>; settings: Record<string, unknown>; }
export interface LandingProperty { id: string; title: string; description: string | null; location: string | null; type: string; purpose: string; salePrice: string | null; rentPrice: string | null; totalArea: string | null; usefulArea: string | null; landArea: string | null; builtArea: string | null; areaUnit: string; bedrooms: number | null; suites: number | null; bathrooms: number | null; parkingSpaces: number | null; amenities: string[]; condominiumAmenities: string[]; viewCount: number; imageUrl: string | null; imageUrls: string[]; publicLatitude?: number | null; publicLongitude?: number | null; siteAddressVisibility?: "hidden" | "neighborhood" | "street" | "full"; }
export interface PublicIdentity { name: string; description: string | null; logoUrl: string | null; email: string | null; phone: string | null; whatsapp: string | null; instagramUrl: string | null; creci: string | null; address: string | null; }
export interface LandingPageDocument { id: string; name: string; slug: string; templateId: string; templateVersion: number; schemaVersion: number; status: LandingStatus; theme: LandingTheme; seo: LandingSeo; identity: PublicIdentity; sections: LandingSection[]; properties: LandingProperty[]; catalogProperties?: LandingProperty[]; publishedAt: string | null; updatedAt: string; }
export const defaultTheme: LandingTheme = { primaryColor: "#2028FF", secondaryColor: "#5D5BFF", backgroundColor: "#FFFFFF", surfaceColor: "#F3F4FF", textColor: "#16182A", mutedTextColor: "#686D7D", buttonTextColor: "#FFFFFF", borderColor: "#DFE1F0" };
export const defaultCatalogSettings: LandingCatalogSettings = { title: "Imóveis selecionados", description: "Uma seleção de propriedades que traduzem o melhor da nossa região.", backLabel: "← Voltar para a landing page", breadcrumbHomeLabel: "Início", searchLabel: "Buscar", favoritesLabel: "Favoritos", primaryColor: defaultTheme.primaryColor, backgroundColor: defaultTheme.backgroundColor, surfaceColor: defaultTheme.surfaceColor, textColor: defaultTheme.textColor, mutedTextColor: defaultTheme.mutedTextColor, buttonTextColor: defaultTheme.buttonTextColor, borderColor: defaultTheme.borderColor };
export const defaultPropertySettings: LandingPropertySettings = { backLabel: "← Voltar para a landing page", breadcrumbHomeLabel: "Início", photosLabel: "Ver todas as fotos", contactButtonLabel: "Falar sobre esse imóvel", saveLabel: "♡ Salvar imóvel", savedLabel: "♥ Salvo", shareLabel: "↗ Compartilhar", aboutTitle: "Sobre o imóvel", featuresTitle: "Características", valuationTitle: "Valorização da região", proximityTitle: "Proximidades", nearbyTitle: "Tudo o que você precisa, a poucos minutos de casa", similarTitle: "Imóveis semelhantes", similarActionLabel: "Ver todos os imóveis", primaryColor: defaultTheme.primaryColor, backgroundColor: defaultTheme.backgroundColor, surfaceColor: defaultTheme.surfaceColor, textColor: defaultTheme.textColor, mutedTextColor: defaultTheme.mutedTextColor, buttonTextColor: defaultTheme.buttonTextColor, borderColor: defaultTheme.borderColor };
export const sectionLabels: Record<LandingSectionType, string> = { navigation: "Navegação", hero: "Capa", "featured-properties": "Imóveis em destaque", about: "Sobre", services: "Como posso ajudar", regions: "Regiões atendidas", contact: "Fale comigo", footer: "Rodapé", custom: "Seção personalizada" };
