import type { LandingSection, LandingSectionType, LandingTheme } from "./model";
import { defaultTheme } from "./model";
export interface LandingTemplate { id: string; version: number; name: string; description: string; supportedSections: LandingSectionType[]; defaultTheme: LandingTheme; createSections(): LandingSection[]; }
const section=(type:LandingSectionType,order:number,content:Record<string,unknown>):LandingSection=>({id:crypto.randomUUID(),type,order,visible:true,content,settings:{}});
export const classicTemplate:LandingTemplate={id:"classic-real-estate",version:1,name:"Clássico imobiliário",description:"Apresentação elegante, editorial e focada em imóveis.",supportedSections:["navigation","hero","featured-properties","about","services","regions","contact","footer"],defaultTheme,createSections:()=>[
 section("navigation",0,{propertiesLabel:"Imóveis",propertiesLink:"#imoveis",advertiseLabel:"Anunciar",advertiseLink:"#contato",aboutLabel:"Sobre mim",aboutLink:"#sobre",favoriteLabel:"Favoritos"}),
 section("hero",1,{title:"Imóveis que combinam com o seu próximo capítulo.",description:"Encontre oportunidades selecionadas para morar, investir ou transformar seus planos em um novo endereço.",buttonLabel:"Ver imóveis",buttonLink:"#imoveis",imageUrl:"",marketYearsValue:"+10 anos",marketYearsLabel:"de mercado",propertiesStatLabel:"no portfólio",credentialStatLabel:"corretor credenciado",locationStatLabel:"atuação especializada"}),
 section("featured-properties",2,{title:"Imóveis em destaque",description:"Oportunidades selecionadas para quem busca comprar, investir ou encontrar o imóvel certo.",images:Array.from({length:9},()=>({visible:true,imageUrl:"",imageStorageKey:""}))}),
 section("about",3,{eyebrow:"Prazer, sou seu consultor",title:"Atendimento próximo e estratégico",description:"Conte com conhecimento de mercado, transparência e atenção aos detalhes em cada etapa.",imageUrl:""}),
 section("services",4,{title:"Como posso ajudar",items:[{title:"Encontrar seu imóvel",description:"Curadoria alinhada ao seu perfil."},{title:"Vender seu imóvel",description:"Estratégia de divulgação e negociação."},{title:"Investir em imóveis",description:"Análise de oportunidades."},{title:"Avaliar seu imóvel",description:"Posicionamento técnico de mercado."}]}),
 section("regions",5,{title:"Regiões atendidas",description:"Atuação nas áreas mais valorizadas da sua região.",allowAdditionalItems:true,items:[{visible:true,title:"Centro",imageUrl:""},{visible:true,title:"Região Norte",imageUrl:""},{visible:true,title:"Região Sul",imageUrl:""},{visible:true,title:"Região Metropolitana",imageUrl:""}]}),
 section("contact",6,{title:"Fale comigo",description:"Seja para comprar, vender ou investir, conte um pouco sobre o que você procura. Entrarei em contato para entender seu momento e apresentar os próximos passos.",officeLabel:"Escritório",whatsappInfoLabel:"WhatsApp",emailInfoLabel:"E-mail",websiteLabel:"Website",websiteValue:"seusite.com.br",creciLabel:"CRECI",nameLabel:"Nome completo",whatsappLabel:"WhatsApp",emailLabel:"E-mail",interestLabel:"Interesse",buyerOptionLabel:"Comprar ou alugar",captureOptionLabel:"Anunciar meu imóvel",messageLabel:"Mensagem",buttonLabel:"Enviar mensagem",successMessage:"Mensagem enviada. Em breve entraremos em contato."}),
 section("footer",7,{description:"Imóveis selecionados para quem busca comprar, vender ou investir com mais segurança.",navigationTitle:"Navegação",navigationItems:[{title:"Início",link:"#inicio"},{title:"Imóveis",link:"#imoveis"},{title:"Anunciar imóvel",link:"#contato"},{title:"Sobre mim",link:"#sobre"},{title:"Contato",link:"#contato"}],regionsTitle:"Regiões atendidas",regionItems:[{title:"Centro",link:"#regioes"},{title:"Região Norte",link:"#regioes"},{title:"Região Sul",link:"#regioes"},{title:"Região Metropolitana",link:"#regioes"}],instagramUrl:"",tiktokUrl:"",youtubeUrl:"",privacyLabel:"Política de Privacidade",privacyLink:"#",developerLabel:"Desenvolvido por",copyrightText:"Todos os direitos reservados."})
]};
export const landingTemplateRegistry={[classicTemplate.id]:classicTemplate} as const;
